In [8]:
!huggingface-cli login

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To log in, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible):
Add token as git credential? (Y/n) Y
Token is valid (permission: fineGrained).
The token `idl project code llama` has been saved to /root/.cache/huggingface/stored_tokens
Cannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' credential helper as default.

git config --global credential.helper store

Read https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage for more details.
Token has not been saved to git credential helper.
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `idl project code llama`

In [7]:
!pip install bitsandbytes accelerate

Collecting bitsandbytes
  Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.3.0)
Requirement already satisfied: torch<3,>=2.0 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.6.0+cu124)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate) (6.0.2)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.28.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2024.10.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3,>=2.0->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3,>=2.0->bitsandbytes) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2025.1.31)
Downloading bitsandbytes-0.45.3-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 24.7 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.3 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 117.9 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 87.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 9.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 37.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 9.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 95.8 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bitsandbytes
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bitsandbytes-0.45.3 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [6]:
!git clone https://github.com/openai/human-eval
!pip install -e human-eval

Cloning into 'human-eval'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 34 (delta 12), reused 7 (delta 7), pack-reused 8 (from 1)
Receiving objects: 100% (34/34), 55.80 KiB | 1.74 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Obtaining file:///content/human-eval
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from human-eval==1.0) (4.67.1)
Collecting fire (from human-eval==1.0)
  Downloading fire-0.7.0.tar.gz (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from human-eval==1.0) (1.26.4)
Requirement already satisfied: termcolor in /usr/local/lib/python3.11/dist-packages (from fire->human-eval==1.0) (2.5.0)
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.7.0-py3-none-any.whl size=114249 sha256=5d410b870fb793c30bb0eaf59314d95ab4a34bd96e18991d32ef65c8f8e9bfa6
  Stored in directory: /root/.cache/pip/wheels/46/54/24/1624fd5b8674eb1188623f7e8e17cdf7c0f6c24b609dfb8a89
Successfully built fire
Installing collected packages: fire, human-eval
  Running setup.py develop for human-eval
Successfully installed fire-0.7.0 human-eval-1.0

In [9]:
%cd human-eval

/content/human-eval

In [ ]:
from human_eval.data import read_problems, write_jsonl
import itertools
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm

# Step 1: Load the HumanEval problems
problems = read_problems()

# Step 2: Get the first 10 problem IDs
first_10_keys = list(itertools.islice(problems.keys(), 5))

# Step 3: Load your model and tokenizer
model_name = "meta-llama/CodeLlama-7b-Python-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
model.to("cuda" if torch.cuda.is_available() else "cpu")

# Step 4: Generate completions for each prompt
samples = []
for problem_id in tqdm(first_10_keys):
    prompt = problems[problem_id]["prompt"]

    print(prompt)

    # Tokenize the prompt
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    # Generate text
    outputs = model.generate(
        inputs.input_ids,
        max_length=500,
        temperature=0.2,
        top_p=0.95,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
    )

    # Decode the generated text
    generated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Important: The completion should NOT include the prompt itself
    # We need to extract just the completion part
    completion = generated_code[len(prompt):]

    # Save the result
    samples.append({
        "task_id": problem_id,
        "completion": completion
    })

    # Print for debugging
    print(f"Problem ID: {problem_id}")
    print("=" * 40)
    print("Prompt + Completion:")
    print(generated_code)
    print("=" * 40)
    print("Just Completion:")
    print(completion)
    print("\n")

# Step 5: Save the samples to a JSONL file
write_jsonl("humaneval_samples.jsonl", samples)

# !evaluate_functional_correctness humaneval_samples.jsonl

In [38]:
from human_eval.data import write_jsonl, read_problems
import itertools

# Load all problems
problems = read_problems()

# Get the first 10 problem IDs
first_10_keys = list(itertools.islice(problems.keys(), 5))

# Create a dictionary with just those 10 problems
selected_problems = {k: problems[k] for k in first_10_keys}

write_jsonl("selected_problems.jsonl",
            [{"task_id": k, **v} for k, v in selected_problems.items()])

In [39]:
!evaluate_functional_correctness humaneval_samples.jsonl --problem_file=selected_problems.jsonl

Reading samples...
5it [00:00, 359.08it/s]
Running test suites...
100% 5/5 [00:00<00:00, 101.72it/s]
Writing results to humaneval_samples.jsonl_results.jsonl...
100% 5/5 [00:00<00:00, 12929.42it/s]
{'pass@1': 0.8}

In [35]:
!python3 results.py

In [56]:
!python main.py

Creating subset of 164 problems...
Saved 164 problems to selected_problems.jsonl
Loading model: meta-llama/CodeLlama-7b-Python-hf
2025-03-15 22:04:22.771064: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742076262.790474   64660 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742076262.797067   64660 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Loading checkpoint shards: 100% 2/2 [00:07<00:00,  3.88s/it]
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
The new lm_head weights will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
Generating completions for 164 problems...
  0% 0/164 [00:00<?, ?it/s]from typing import List


def has_close_elements(numbers: List[float], threshold: float) -> bool:
    """ Check if in given list of numbers, are any two numbers closer to each other than
    given threshold.
    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)
    False
    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)
    True
    """

  1% 1/164 [00:05<16:01,  5.90s/it]from typing import List


def separate_paren_groups(paren_string: str) -> List[str]:
    """ Input to this function is a string containing multiple groups of nested parentheses. Your goal is to
    separate those group into separate strings and return the list of those.
    Separate groups are balanced (each open brace is properly closed) and not nested within each other
    Ignore any spaces in the input string.
    >>> separate_paren_groups('( ) (( )) (( )( ))')
    ['()', '(())', '(()())']
    """

  1% 2/164 [00:59<1:31:55, 34.05s/it]

def truncate_number(number: float) -> float:
    """ Given a positive floating point number, it can be decomposed into
    and integer part (largest integer smaller than given number) and decimals
    (leftover part always smaller than 1).

    Return the decimal part of the number.
    >>> truncate_number(3.5)
    0.5
    """

  2% 3/164 [01:14<1:07:20, 25.10s/it]from typing import List


def below_zero(operations: List[int]) -> bool:
    """ You're given a list of deposit and withdrawal operations on a bank account that starts with
    zero balance. Your task is to detect if at any point the balance of account fallls below zero, and
    at that point function should return True. Otherwise it should return False.
    >>> below_zero([1, 2, 3])
    False
    >>> below_zero([1, 2, -4, 5])
    True
    """

  2% 4/164 [01:17<44:05, 16.53s/it]  from typing import List


def mean_absolute_deviation(numbers: List[float]) -> float:
    """ For a given list of input numbers, calculate Mean Absolute Deviation
    around the mean of this dataset.
    Mean Absolute Deviation is the average absolute difference between each
    element and a centerpoint (mean in this case):
    MAD = average | x - x_mean |
    >>> mean_absolute_deviation([1.0, 2.0, 3.0, 4.0])
    1.0
    """

  3% 5/164 [01:21<31:37, 11.93s/it]from typing import List


def intersperse(numbers: List[int], delimeter: int) -> List[int]:
    """ Insert a number 'delimeter' between every two consecutive elements of input list `numbers'
    >>> intersperse([], 4)
    []
    >>> intersperse([1, 2, 3], 4)
    [1, 4, 2, 4, 3]
    """

  4% 6/164 [01:24<23:38,  8.98s/it]from typing import List


def parse_nested_parens(paren_string: str) -> List[int]:
    """ Input to this function is a string represented multiple groups for nested parentheses separated by spaces.
    For each of the group, output the deepest level of nesting of parentheses.
    E.g. (()()) has maximum two levels of nesting while ((())) has three.

    >>> parse_nested_parens('(()()) ((())) () ((())()())')
    [2, 3, 1, 3]
    """

  4% 7/164 [01:41<30:15, 11.57s/it]from typing import List


def filter_by_substring(strings: List[str], substring: str) -> List[str]:
    """ Filter an input list of strings only for ones that contain given substring
    >>> filter_by_substring([], 'a')
    []
    >>> filter_by_substring(['abc', 'bacd', 'cde', 'array'], 'a')
    ['abc', 'bacd', 'array']
    """

  5% 8/164 [01:44<23:01,  8.85s/it]from typing import List, Tuple


def sum_product(numbers: List[int]) -> Tuple[int, int]:
    """ For a given list of integers, return a tuple consisting of a sum and a product of all the integers in a list.
    Empty sum should be equal to 0 and empty product should be equal to 1.
    >>> sum_product([])
    (0, 1)
    >>> sum_product([1, 2, 3, 4])
    (10, 24)
    """

  5% 9/164 [01:48<18:36,  7.20s/it]from typing import List, Tuple


def rolling_max(numbers: List[int]) -> List[int]:
    """ From a given list of integers, generate a list of rolling maximum element found until given moment
    in the sequence.
    >>> rolling_max([1, 2, 3, 2, 3, 4, 2])
    [1, 2, 3, 3, 3, 4, 4]
    """

  6% 10/164 [02:19<38:05, 14.84s/it]

def is_palindrome(string: str) -> bool:
    """ Test if given string is a palindrome """
    return string == string[::-1]


def make_palindrome(string: str) -> str:
    """ Find the shortest palindrome that begins with a supplied string.
    Algorithm idea is simple:
    - Find the longest postfix of supplied string that is a palindrome.
    - Append to the end of the string reverse of a string prefix that comes before the palindromic suffix.
    >>> make_palindrome('')
    ''
    >>> make_palindrome('cat')
    'catac'
    >>> make_palindrome('cata')
    'catac'
    """

  7% 11/164 [02:27<32:03, 12.57s/it]from typing import List


def string_xor(a: str, b: str) -> str:
    """ Input are two strings a and b consisting only of 1s and 0s.
    Perform binary XOR on these inputs and return result also as a string.
    >>> string_xor('010', '110')
    '100'
    """

  7% 12/164 [02:37<29:43, 11.73s/it]from typing import List, Optional


def longest(strings: List[str]) -> Optional[str]:
    """ Out of list of strings, return the longest one. Return the first one in case of multiple
    strings of the same length. Return None in case the input list is empty.
    >>> longest([])

    >>> longest(['a', 'b', 'c'])
    'a'
    >>> longest(['a', 'bb', 'ccc'])
    'ccc'
    """

  8% 13/164 [02:42<24:17,  9.65s/it]

def greatest_common_divisor(a: int, b: int) -> int:
    """ Return a greatest common divisor of two integers a and b
    >>> greatest_common_divisor(3, 5)
    1
    >>> greatest_common_divisor(25, 15)
    5
    """

  9% 14/164 [02:47<20:41,  8.28s/it]from typing import List


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string
    >>> all_prefixes('abc')
    ['a', 'ab', 'abc']
    """

  9% 15/164 [02:49<16:25,  6.62s/it]

def string_sequence(n: int) -> str:
    """ Return a string containing space-delimited numbers starting from 0 upto n inclusive.
    >>> string_sequence(0)
    '0'
    >>> string_sequence(5)
    '0 1 2 3 4 5'
    """

 10% 16/164 [03:29<41:05, 16.66s/it]

def count_distinct_characters(string: str) -> int:
    """ Given a string, find out how many distinct characters (regardless of case) does it consist of
    >>> count_distinct_characters('xyzXYZ')
    3
    >>> count_distinct_characters('Jerry')
    4
    """

 10% 17/164 [03:32<30:45, 12.55s/it]from typing import List


def parse_music(music_string: str) -> List[int]:
    """ Input to this function is a string representing musical notes in a special ASCII format.
    Your task is to parse this string and return list of integers corresponding to how many beats does each
    not last.

    Here is a legend:
    'o' - whole note, lasts four beats
    'o|' - half note, lasts two beats
    '.|' - quater note, lasts one beat

    >>> parse_music('o o| .| o| o| .| .| .| .| o o')
    [4, 2, 1, 2, 2, 1, 1, 1, 1, 4, 4]
    """

 11% 18/164 [03:36<23:50,  9.80s/it]

def how_many_times(string: str, substring: str) -> int:
    """ Find how many times a given substring can be found in the original string. Count overlaping cases.
    >>> how_many_times('', 'a')
    0
    >>> how_many_times('aaa', 'a')
    3
    >>> how_many_times('aaaa', 'aa')
    3
    """

 12% 19/164 [03:40<19:47,  8.19s/it]from typing import List


def sort_numbers(numbers: str) -> str:
    """ Input is a space-delimited string of numberals from 'zero' to 'nine'.
    Valid choices are 'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight' and 'nine'.
    Return the string with numbers sorted from smallest to largest
    >>> sort_numbers('three one five')
    'one three five'
    """

 12% 20/164 [04:15<38:51, 16.19s/it]from typing import List, Tuple


def find_closest_elements(numbers: List[float]) -> Tuple[float, float]:
    """ From a supplied list of numbers (of length at least two) select and return two that are the closest to each
    other and return them in order (smaller number, larger number).
    >>> find_closest_elements([1.0, 2.0, 3.0, 4.0, 5.0, 2.2])
    (2.0, 2.2)
    >>> find_closest_elements([1.0, 2.0, 3.0, 4.0, 5.0, 2.0])
    (2.0, 2.0)
    """

 13% 21/164 [04:23<32:28, 13.62s/it]from typing import List


def rescale_to_unit(numbers: List[float]) -> List[float]:
    """ Given list of numbers (of at least two elements), apply a linear transform to that list,
    such that the smallest number will become 0 and the largest will become 1
    >>> rescale_to_unit([1.0, 2.0, 3.0, 4.0, 5.0])
    [0.0, 0.25, 0.5, 0.75, 1.0]
    """

 13% 22/164 [04:26<24:34, 10.38s/it]from typing import List, Any


def filter_integers(values: List[Any]) -> List[int]:
    """ Filter given list of any python values only for integers
    >>> filter_integers(['a', 3.14, 5])
    [5]
    >>> filter_integers([1, 2, 3, 'abc', {}, []])
    [1, 2, 3]
    """

 14% 23/164 [04:28<18:56,  8.06s/it]

def strlen(string: str) -> int:
    """ Return length of given string
    >>> strlen('')
    0
    >>> strlen('abc')
    3
    """

 15% 24/164 [04:30<14:30,  6.22s/it]

def largest_divisor(n: int) -> int:
    """ For a given number n, find the largest number that divides n evenly, smaller than n
    >>> largest_divisor(15)
    5
    """

 15% 25/164 [05:24<47:19, 20.43s/it]from typing import List


def factorize(n: int) -> List[int]:
    """ Return list of prime factors of given integer in the order from smallest to largest.
    Each of the factors should be listed number of times corresponding to how many times it appeares in factorization.
    Input number should be equal to the product of all factors
    >>> factorize(8)
    [2, 2, 2]
    >>> factorize(25)
    [5, 5]
    >>> factorize(70)
    [2, 5, 7]
    """

 16% 26/164 [05:26<34:14, 14.89s/it]from typing import List


def remove_duplicates(numbers: List[int]) -> List[int]:
    """ From a list of integers, remove all elements that occur more than once.
    Keep order of elements left the same as in the input.
    >>> remove_duplicates([1, 2, 3, 2, 4])
    [1, 3, 4]
    """

 16% 27/164 [05:30<26:32, 11.63s/it]

def flip_case(string: str) -> str:
    """ For a given string, flip lowercase characters to uppercase and uppercase to lowercase.
    >>> flip_case('Hello')
    'hELLO'
    """

 17% 28/164 [05:34<21:06,  9.31s/it]from typing import List


def concatenate(strings: List[str]) -> str:
    """ Concatenate list of strings into a single string
    >>> concatenate([])
    ''
    >>> concatenate(['a', 'b', 'c'])
    'abc'
    """

 18% 29/164 [05:36<16:00,  7.12s/it]from typing import List


def filter_by_prefix(strings: List[str], prefix: str) -> List[str]:
    """ Filter an input list of strings only for ones that start with a given prefix.
    >>> filter_by_prefix([], 'a')
    []
    >>> filter_by_prefix(['abc', 'bcd', 'cde', 'array'], 'a')
    ['abc', 'array']
    """

 18% 30/164 [06:30<47:24, 21.23s/it]

def get_positive(l: list):
    """Return only positive numbers in the list.
    >>> get_positive([-1, 2, -4, 5, 6])
    [2, 5, 6]
    >>> get_positive([5, 3, -5, 2, -3, 3, 9, 0, 123, 1, -10])
    [5, 3, 2, 3, 9, 123, 1]
    """

 19% 31/164 [06:32<34:29, 15.56s/it]

def is_prime(n):
    """Return true if a given number is prime, and false otherwise.
    >>> is_prime(6)
    False
    >>> is_prime(101)
    True
    >>> is_prime(11)
    True
    >>> is_prime(13441)
    True
    >>> is_prime(61)
    True
    >>> is_prime(4)
    False
    >>> is_prime(1)
    False
    """

 20% 32/164 [06:35<26:11, 11.90s/it]import math


def poly(xs: list, x: float):
    """
    Evaluates polynomial with coefficients xs at point x.
    return xs[0] + xs[1] * x + xs[1] * x^2 + .... xs[n] * x^n
    """
    return sum([coeff * math.pow(x, i) for i, coeff in enumerate(xs)])


def find_zero(xs: list):
    """ xs are coefficients of a polynomial.
    find_zero find x such that poly(x) = 0.
    find_zero returns only only zero point, even if there are many.
    Moreover, find_zero only takes list xs having even number of coefficients
    and largest non zero coefficient as it guarantees
    a solution.
    >>> round(find_zero([1, 2]), 2) # f(x) = 1 + 2x
    -0.5
    >>> round(find_zero([-6, 11, -6, 1]), 2) # (x - 1) * (x - 2) * (x - 3) = -6 + 11x - 6x^2 + x^3
    1.0
    """

 20% 33/164 [07:30<53:39, 24.58s/it]

def sort_third(l: list):
    """This function takes a list l and returns a list l' such that
    l' is identical to l in the indicies that are not divisible by three, while its values at the indicies that are divisible by three are equal
    to the values of the corresponding indicies of l, but sorted.
    >>> sort_third([1, 2, 3])
    [1, 2, 3]
    >>> sort_third([5, 6, 3, 4, 8, 9, 2])
    [2, 6, 3, 4, 8, 9, 5]
    """

 21% 34/164 [07:37<42:01, 19.40s/it]

def unique(l: list):
    """Return sorted unique elements in a list
    >>> unique([5, 3, 5, 2, 3, 3, 9, 0, 123])
    [0, 2, 3, 5, 9, 123]
    """

 21% 35/164 [08:31<1:03:53, 29.72s/it]

def max_element(l: list):
    """Return maximum element in the list.
    >>> max_element([1, 2, 3])
    3
    >>> max_element([5, 3, -5, 2, -3, 3, 9, 0, 123, 1, -10])
    123
    """

 22% 36/164 [08:31<44:39, 20.93s/it]

def fizz_buzz(n: int):
    """Return the number of times the digit 7 appears in integers less than n which are divisible by 11 or 13.
    >>> fizz_buzz(50)
    0
    >>> fizz_buzz(78)
    2
    >>> fizz_buzz(79)
    3
    """

 23% 37/164 [08:52<44:22, 20.97s/it]

def sort_even(l: list):
    """This function takes a list l and returns a list l' such that
    l' is identical to l in the odd indicies, while its values at the even indicies are equal
    to the values of the even indicies of l, but sorted.
    >>> sort_even([1, 2, 3])
    [1, 2, 3]
    >>> sort_even([5, 6, 3, 4])
    [3, 6, 5, 4]
    """

 23% 38/164 [08:57<33:39, 16.03s/it]

def encode_cyclic(s: str):
    """
    returns encoded string by cycling groups of three characters.
    """
    # split string to groups. Each of length 3.
    groups = [s[(3 * i):min((3 * i + 3), len(s))] for i in range((len(s) + 2) // 3)]
    # cycle elements in each group. Unless group has fewer elements than 3.
    groups = [(group[1:] + group[0]) if len(group) == 3 else group for group in groups]
    return "".join(groups)


def decode_cyclic(s: str):
    """
    takes as input string encoded with encode_cyclic function. Returns decoded string.
    """

 24% 39/164 [09:51<57:21, 27.54s/it]

def prime_fib(n: int):
    """
    prime_fib returns n-th number that is a Fibonacci number and it's also prime.
    >>> prime_fib(1)
    2
    >>> prime_fib(2)
    3
    >>> prime_fib(3)
    5
    >>> prime_fib(4)
    13
    >>> prime_fib(5)
    89
    """

 24% 40/164 [09:59<44:42, 21.63s/it]

def triples_sum_to_zero(l: list):
    """
    triples_sum_to_zero takes a list of integers as an input.
    it returns True if there are three distinct elements in the list that
    sum to zero, and False otherwise.

    >>> triples_sum_to_zero([1, 3, 5, 0])
    False
    >>> triples_sum_to_zero([1, 3, -2, 1])
    True
    >>> triples_sum_to_zero([1, 2, 3, 7])
    False
    >>> triples_sum_to_zero([2, 4, -5, 3, 9, 7])
    True
    >>> triples_sum_to_zero([1])
    False
    """

 25% 41/164 [10:12<39:07, 19.08s/it]

def car_race_collision(n: int):
    """
    Imagine a road that's a perfectly straight infinitely long line.
    n cars are driving left to right;  simultaneously, a different set of n cars
    are driving right to left.   The two sets of cars start out being very far from
    each other.  All cars move in the same speed.  Two cars are said to collide
    when a car that's moving left to right hits a car that's moving right to left.
    However, the cars are infinitely sturdy and strong; as a result, they continue moving
    in their trajectory as if they did not collide.

    This function outputs the number of such collisions.
    """

 26% 42/164 [10:25<34:57, 17.19s/it]

def incr_list(l: list):
    """Return list with elements incremented by 1.
    >>> incr_list([1, 2, 3])
    [2, 3, 4]
    >>> incr_list([5, 3, 5, 2, 3, 3, 9, 0, 123])
    [6, 4, 6, 3, 4, 4, 10, 1, 124]
    """

 26% 43/164 [10:27<25:38, 12.71s/it]

def pairs_sum_to_zero(l):
    """
    pairs_sum_to_zero takes a list of integers as an input.
    it returns True if there are two distinct elements in the list that
    sum to zero, and False otherwise.
    >>> pairs_sum_to_zero([1, 3, 5, 0])
    False
    >>> pairs_sum_to_zero([1, 3, -2, 1])
    False
    >>> pairs_sum_to_zero([1, 2, 3, 7])
    False
    >>> pairs_sum_to_zero([2, 4, -5, 3, 5, 7])
    True
    >>> pairs_sum_to_zero([1])
    False
    """

 27% 44/164 [10:34<21:46, 10.89s/it]

def change_base(x: int, base: int):
    """Change numerical base of input number x to base.
    return string representation after the conversion.
    base numbers are less than 10.
    >>> change_base(8, 3)
    '22'
    >>> change_base(8, 2)
    '1000'
    >>> change_base(7, 2)
    '111'
    """

 27% 45/164 [10:39<17:57,  9.05s/it]

def triangle_area(a, h):
    """Given length of a side and high return area for a triangle.
    >>> triangle_area(5, 3)
    7.5
    """

 28% 46/164 [11:34<44:55, 22.85s/it]

def fib4(n: int):
    """The Fib4 number sequence is a sequence similar to the Fibbonacci sequnece that's defined as follows:
    fib4(0) -> 0
    fib4(1) -> 0
    fib4(2) -> 2
    fib4(3) -> 0
    fib4(n) -> fib4(n-1) + fib4(n-2) + fib4(n-3) + fib4(n-4).
    Please write a function to efficiently compute the n-th element of the fib4 number sequence.  Do not use recursion.
    >>> fib4(5)
    4
    >>> fib4(6)
    8
    >>> fib4(7)
    14
    """

 29% 47/164 [11:40<34:59, 17.95s/it]

def median(l: list):
    """Return median of elements in the list l.
    >>> median([3, 1, 2, 4, 5])
    3
    >>> median([-10, 4, 6, 1000, 10, 20])
    15.0
    """

 29% 48/164 [11:47<28:33, 14.77s/it]

def is_palindrome(text: str):
    """
    Checks if given string is a palindrome
    >>> is_palindrome('')
    True
    >>> is_palindrome('aba')
    True
    >>> is_palindrome('aaaaa')
    True
    >>> is_palindrome('zbcd')
    False
    """

 30% 49/164 [11:51<22:05, 11.53s/it]

def modp(n: int, p: int):
    """Return 2^n modulo p (be aware of numerics).
    >>> modp(3, 5)
    3
    >>> modp(1101, 101)
    2
    >>> modp(0, 101)
    1
    >>> modp(3, 11)
    8
    >>> modp(100, 101)
    1
    """

 30% 50/164 [12:31<37:46, 19.88s/it]


In [55]:
!python3 results.py

Reading results from: humaneval_samples.jsonl_results.jsonl

===== RESULTS SUMMARY =====
Total problems: 5
Passed: 4
Failed: 1
Pass rate: 80.00%

===== DETAILED RESULTS =====
HumanEval/0: ✓ PASSED
HumanEval/1: ✗ FAILED
HumanEval/2: ✓ PASSED
HumanEval/3: ✓ PASSED
HumanEval/4: ✓ PASSED

In [45]:
import gzip
import json

# Path to the gzipped file
file_path = '/content/human-eval/data/HumanEval.jsonl.gz'

# Count problems
problem_count = 0
task_ids = []

# Open and read the gzipped file
with gzip.open(file_path, 'rt', encoding='utf-8') as f:
    for line in f:
        data = json.loads(line.strip())
        problem_count += 1
        if 'task_id' in data:
            task_ids.append(data['task_id'])

# Print results
print(f"Total problems in HumanEval.jsonl.gz: {problem_count}")

Total problems in HumanEval.jsonl.gz: 164

In [50]:
from human_eval.data import read_problems
import itertools

# Load all problems from the dataset
problems = read_problems()

# Get the first 5 problem IDs
first_5_keys = list(itertools.islice(problems.keys(), 5))

# Print the prompts for the first 5 problems
for problem_id in first_5_keys:
    print(f"Problem ID: {problem_id}")
    print("=" * 80)
    print(problems[problem_id]["prompt"])
    print("=" * 80)
    print("\n")

Problem ID: HumanEval/0
================================================================================
from typing import List


def has_close_elements(numbers: List[float], threshold: float) -> bool:
    """ Check if in given list of numbers, are any two numbers closer to each other than
    given threshold.
    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)
    False
    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)
    True
    """

================================================================================


Problem ID: HumanEval/1
================================================================================
from typing import List


def separate_paren_groups(paren_string: str) -> List[str]:
    """ Input to this function is a string containing multiple groups of nested parentheses. Your goal is to
    separate those group into separate strings and return the list of those.
    Separate groups are balanced (each open brace is properly closed) and not nested within each other
    Ignore any spaces in the input string.
    >>> separate_paren_groups('( ) (( )) (( )( ))')
    ['()', '(())', '(()())']
    """

================================================================================


Problem ID: HumanEval/2
================================================================================


def truncate_number(number: float) -> float:
    """ Given a positive floating point number, it can be decomposed into
    and integer part (largest integer smaller than given number) and decimals
    (leftover part always smaller than 1).

    Return the decimal part of the number.
    >>> truncate_number(3.5)
    0.5
    """

================================================================================


Problem ID: HumanEval/3
================================================================================
from typing import List


def below_zero(operations: List[int]) -> bool:
    """ You're given a list of deposit and withdrawal operations on a bank account that starts with
    zero balance. Your task is to detect if at any point the balance of account fallls below zero, and
    at that point function should return True. Otherwise it should return False.
    >>> below_zero([1, 2, 3])
    False
    >>> below_zero([1, 2, -4, 5])
    True
    """

================================================================================


Problem ID: HumanEval/4
================================================================================
from typing import List


def mean_absolute_deviation(numbers: List[float]) -> float:
    """ For a given list of input numbers, calculate Mean Absolute Deviation
    around the mean of this dataset.
    Mean Absolute Deviation is the average absolute difference between each
    element and a centerpoint (mean in this case):
    MAD = average | x - x_mean |
    >>> mean_absolute_deviation([1.0, 2.0, 3.0, 4.0])
    1.0
    """

================================================================================

In [234]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df_original = pd.read_csv('/content/human-eval/humaneval_extracted.csv')

# Display the first few rows
df_original

,task_id,prompt,entry_point,canonical_solution,test
0,HumanEval/0,from typing import List\n\n\ndef has_close_ele...,has_close_elements,"for idx, elem in enumerate(numbers):\n ...","\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
1,HumanEval/1,from typing import List\n\n\ndef separate_pare...,separate_paren_groups,result = []\n current_string = []\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
2,HumanEval/2,\n\ndef truncate_number(number: float) -> floa...,truncate_number,return number % 1.0\n,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
3,HumanEval/3,from typing import List\n\n\ndef below_zero(op...,below_zero,balance = 0\n\n for op in operations:\n...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
4,HumanEval/4,from typing import List\n\n\ndef mean_absolute...,mean_absolute_deviation,mean = sum(numbers) / len(numbers)\n re...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
...,...,...,...,...,...
159,HumanEval/159,"\ndef eat(number, need, remaining):\n """"""\n...",eat,if(need <= remaining):\n return [ n...,def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
161,HumanEval/161,"\ndef solve(s):\n """"""You are given a string...",solve,flg = 0\n idx = 0\n new_str = list(s...,def check(candidate):\n\n # Check some simp...
162,HumanEval/162,"\ndef string_to_md5(text):\n """"""\n Given...",string_to_md5,import hashlib\n return hashlib.md5(tex...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...

In [250]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df_completions = pd.read_csv('/content/human-eval/update10.csv')

# Display the first few rows
df_completions

,task_id,completion,prompt
0,HumanEval/0,numbers_to_check = sorted(numbers)\n fo...,from typing import List\n\n\ndef has_close_ele...
1,HumanEval/1,\n parens = []\n # Stack for keeping tr...,from typing import List\n\n\ndef separate_pare...
2,HumanEval/2,return number - int(number)\n\n\ndef is_py...,\n\ndef truncate_number(number: float) -> floa...
3,HumanEval/3,balance = 0\n for operation in operatio...,from typing import List\n\n\ndef below_zero(op...
4,HumanEval/4,numbers_mean = sum(numbers) / len(numbers)...,from typing import List\n\n\ndef mean_absolute...
...,...,...,...
159,HumanEval/159,# TODO - Add Your Code Here - 8 Lines (~3-...,"\ndef eat(number, need, remaining):\n """"""\n..."
160,HumanEval/160,op=operator[0]; operand1=operand[0]; opera...,"\ndef do_algebra(operator, operand):\n """"""\..."
161,HumanEval/161,\n #for i in range (len(s)): ## Loop ...,"\ndef solve(s):\n """"""You are given a string..."
162,HumanEval/162,\n import hashlib\n\n if not text:\n ...,"\ndef string_to_md5(text):\n """"""\n Given..."
163,HumanEval/163,if not (type(a) == int or type(b) == int):...,"\ndef generate_integers(a, b):\n """"""\n G..."

In [251]:
new_df = pd.merge(
    df_completions[['task_id', 'completion']],
    df_original[['task_id', 'prompt']],
    on='task_id',
    how='left'
)
new_df

,task_id,completion,prompt
0,HumanEval/0,numbers_to_check = sorted(numbers)\n fo...,from typing import List\n\n\ndef has_close_ele...
1,HumanEval/1,\n parens = []\n # Stack for keeping tr...,from typing import List\n\n\ndef separate_pare...
2,HumanEval/2,return number - int(number)\n\n\ndef is_py...,\n\ndef truncate_number(number: float) -> floa...
3,HumanEval/3,balance = 0\n for operation in operatio...,from typing import List\n\n\ndef below_zero(op...
4,HumanEval/4,numbers_mean = sum(numbers) / len(numbers)...,from typing import List\n\n\ndef mean_absolute...
...,...,...,...
159,HumanEval/159,# TODO - Add Your Code Here - 8 Lines (~3-...,"\ndef eat(number, need, remaining):\n """"""\n..."
160,HumanEval/160,op=operator[0]; operand1=operand[0]; opera...,"\ndef do_algebra(operator, operand):\n """"""\..."
161,HumanEval/161,\n #for i in range (len(s)): ## Loop ...,"\ndef solve(s):\n """"""You are given a string..."
162,HumanEval/162,\n import hashlib\n\n if not text:\n ...,"\ndef string_to_md5(text):\n """"""\n Given..."
163,HumanEval/163,if not (type(a) == int or type(b) == int):...,"\ndef generate_integers(a, b):\n """"""\n G..."

In [252]:
failed_ids = df_completions[
    (df_completions['completion'].isna()) |
    (df_completions['completion'] == '') |
    (df_completions['completion'].astype(str).str.isspace()) |
    (df_completions['completion'].astype(str).str.strip() == '')
]['task_id'].tolist()  # Added ['task_id'] here

failed_questions_df = df_original[df_original['task_id'].isin(failed_ids)]
len(failed_questions_df)

5

In [253]:
failed_questions_df

,task_id,prompt,entry_point,canonical_solution,test
70,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,strange_sort_list,"res, switch = [], True\n while lst:\n ...",def check(candidate):\n\n # Check some simp...
82,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",prime_length,l = len(string)\n if l == 0 or l == 1:\...,def check(candidate):\n\n # Check some simp...
95,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",check_dict_case,if len(dict.keys()) == 0:\n return ...,def check(candidate):\n\n # Check some simp...
127,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",intersection,def is_prime(num):\n if num == 1 or...,def check(candidate):\n\n # Check some simp...
153,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",Strongest_Extension,strong = extensions[0]\n my_val = len([...,def check(candidate):\n\n # Check some simp...

In [254]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from tqdm import tqdm
import re
import pandas as pd

# Load the model
def load_model(model_name="meta-llama/CodeLlama-7b-Python-hf"):
    print(f"Loading model: {model_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = "[PAD]"
        tokenizer.add_special_tokens({"pad_token": "[PAD]"})

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.float16,
    )

    model.resize_token_embeddings(len(tokenizer))

    return model, tokenizer

# Generate solutions directly from the failed_questions_df
def regenerate_solutions(failed_questions_df, model_name="meta-llama/CodeLlama-7b-Python-hf"):
    # Load model
    model, tokenizer = load_model(model_name)

    # Create results list
    results = []

    # Process each problem
    print(f"Regenerating solutions for {len(failed_questions_df)} problems...")

    for _, row in tqdm(failed_questions_df.iterrows(), total=len(failed_questions_df)):
        task_id = row['task_id']
        prompt = row['prompt']

        # Generate solution
        inputs = tokenizer(prompt, return_tensors="pt", padding=True, return_attention_mask=True).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                input_ids=inputs.input_ids,
                attention_mask=inputs.attention_mask,
                max_new_tokens=1024,
                temperature=0.7,
                top_p=0.95,
                do_sample=True,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
                repetition_penalty=1.2,
            )

        # Decode and extract completion
        generated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)
        completion = generated_code[len(prompt):]

        # Store result
        results.append({
            "task_id": task_id,
            "prompt": prompt,
            "completion": completion
        })

    # Convert to DataFrame
    results_df = pd.DataFrame(results)

    print(f"Generated {len(results_df)} new solutions")
    return results_df

# Use it directly
new_solutions_df = regenerate_solutions(failed_questions_df)

# Save results if needed
new_solutions_df.to_csv('regenerated_solutions.csv', index=False)

Loading model: meta-llama/CodeLlama-7b-Python-hf

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Regenerating solutions for 5 problems...

100%|██████████| 5/5 [00:26<00:00,  5.24s/it]

Generated 5 new solutions

In [255]:
new_solutions_df

,task_id,prompt,completion
0,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,# Your code here\n if len(lst) <= 0 :\...
1,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",#your code here\n
2,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",\n # TODO - by the end of this lesson y...
3,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",
4,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",

In [ ]:
new_solutions_df

In [62]:
import gzip
import json
import pandas as pd

# Path to the gzipped JSONL file
file_path = '/content/human-eval/data/HumanEval.jsonl.gz'

# Extract the data and convert to a DataFrame
data = []
with gzip.open(file_path, 'rt', encoding='utf-8') as f:
    for line in f:
        data.append(json.loads(line))

# Convert to DataFrame for easier analysis
df = pd.DataFrame(data)

# Display basic information
print(f"Total records: {len(df)}")
print("\nColumns in the dataset:")
print(df.columns.tolist())

# Display the first few records
print("\nSample data:")
print(df.head())

# Optionally save as a CSV for easier viewing
df.to_csv('humaneval_extracted.csv', index=False)
print("\nData extracted and saved to 'humaneval_extracted.csv'")

Total records: 164

Columns in the dataset:
['task_id', 'prompt', 'entry_point', 'canonical_solution', 'test']

Sample data:
       task_id                                             prompt  \
0  HumanEval/0  from typing import List\n\n\ndef has_close_ele...
1  HumanEval/1  from typing import List\n\n\ndef separate_pare...
2  HumanEval/2  \n\ndef truncate_number(number: float) -> floa...
3  HumanEval/3  from typing import List\n\n\ndef below_zero(op...
4  HumanEval/4  from typing import List\n\n\ndef mean_absolute...

               entry_point                                 canonical_solution  \
0       has_close_elements      for idx, elem in enumerate(numbers):\n    ...
1    separate_paren_groups      result = []\n    current_string = []\n    ...
2          truncate_number                              return number % 1.0\n
3               below_zero      balance = 0\n\n    for op in operations:\n...
4  mean_absolute_deviation      mean = sum(numbers) / len(numbers)\n    re...

                                                test
0  \n\nMETADATA = {\n    'author': 'jt',\n    'da...
1  \n\nMETADATA = {\n    'author': 'jt',\n    'da...
2  \n\nMETADATA = {\n    'author': 'jt',\n    'da...
3  \n\nMETADATA = {\n    'author': 'jt',\n    'da...
4  \n\nMETADATA = {\n    'author': 'jt',\n    'da...

Data extracted and saved to 'humaneval_extracted.csv'

In [66]:
passed_df

,task_id,completion,result,passed
1,HumanEval/1,groups = []\r\n paren_stack = []\r\n ...,failed: list index out of range,False
5,HumanEval/5,if not numbers:\r\n return []\r\n ...,failed:,False
6,HumanEval/6,"""""""\r\n Algorithm:\r\n Use a sta...",failed: Illegal character,False
10,HumanEval/10,if len(string) == 0:\r\n return str...,failed:,False
12,HumanEval/12,longest_string = ''\r\n longest_string_...,failed:,False
...,...,...,...,...
158,HumanEval/158,max_length = 0\r\n max_str = None\r\n ...,failed: t2,False
159,HumanEval/159,if (number < need):\r\n return [num...,failed: Error,False
160,HumanEval/160,"return sum([int(operand[i])*eval(f""{operat...","failed: invalid syntax (<string>, line 1)",False
161,HumanEval/161,if s.isalpha():\r\n return s.swapca...,failed:,False
163,HumanEval/163,if a > b:\r\n return []\r\n else...,failed: Test 1,False

In [67]:
df

,task_id,prompt,entry_point,canonical_solution,test
0,HumanEval/0,from typing import List\n\n\ndef has_close_ele...,has_close_elements,"for idx, elem in enumerate(numbers):\n ...","\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
1,HumanEval/1,from typing import List\n\n\ndef separate_pare...,separate_paren_groups,result = []\n current_string = []\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
2,HumanEval/2,\n\ndef truncate_number(number: float) -> floa...,truncate_number,return number % 1.0\n,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
3,HumanEval/3,from typing import List\n\n\ndef below_zero(op...,below_zero,balance = 0\n\n for op in operations:\n...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
4,HumanEval/4,from typing import List\n\n\ndef mean_absolute...,mean_absolute_deviation,mean = sum(numbers) / len(numbers)\n re...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
...,...,...,...,...,...
159,HumanEval/159,"\ndef eat(number, need, remaining):\n """"""\n...",eat,if(need <= remaining):\n return [ n...,def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
161,HumanEval/161,"\ndef solve(s):\n """"""You are given a string...",solve,flg = 0\n idx = 0\n new_str = list(s...,def check(candidate):\n\n # Check some simp...
162,HumanEval/162,"\ndef string_to_md5(text):\n """"""\n Given...",string_to_md5,import hashlib\n return hashlib.md5(tex...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...

In [68]:
failed_ids = passed_df[passed_df['passed'] == False]['task_id'].tolist()
# Or if it's a string: results_df[results_df['passed'] == "FALSE"]['task_id'].tolist()

# 4. Filter the original data to get just the failed questions
failed_questions_df = df[df['task_id'].isin(failed_ids)]
failed_questions_df

,task_id,prompt,entry_point,canonical_solution,test
1,HumanEval/1,from typing import List\n\n\ndef separate_pare...,separate_paren_groups,result = []\n current_string = []\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
5,HumanEval/5,from typing import List\n\n\ndef intersperse(n...,intersperse,if not numbers:\n return []\n\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
6,HumanEval/6,from typing import List\n\n\ndef parse_nested_...,parse_nested_parens,def parse_paren_group(s):\n depth =...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
10,HumanEval/10,\n\ndef is_palindrome(string: str) -> bool:\n ...,make_palindrome,if not string:\n return ''\n\n b...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
12,HumanEval/12,"from typing import List, Optional\n\n\ndef lon...",longest,if not strings:\n return None\n\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
...,...,...,...,...,...
158,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",find_max,"return sorted(words, key = lambda x: (-len...",def check(candidate):\n\n # Check some simp...
159,HumanEval/159,"\ndef eat(number, need, remaining):\n """"""\n...",eat,if(need <= remaining):\n return [ n...,def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
161,HumanEval/161,"\ndef solve(s):\n """"""You are given a string...",solve,flg = 0\n idx = 0\n new_str = list(s...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...

In [69]:
!python repress.py --model "meta-llama/CodeLlama-7b-Python-hf" --results_file "failedresults.jsonl"

Loading failed tasks...
Traceback (most recent call last):
  File "/content/human-eval/repress.py", line 183, in <module>
    main()
  File "/content/human-eval/repress.py", line 50, in main
    failed_tasks = load_results(args.results_file)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/human-eval/repress.py", line 26, in load_results
    with open(results_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'failedresults.jsonl'

In [138]:
failed_questions_df

,task_id,prompt,entry_point,canonical_solution,test
26,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,remove_duplicates,import collections\n c = collections.Co...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
46,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...",fib4,"results = [0, 0, 2, 0]\n if n < 4:\n ...",\n\nMETADATA = {}\n\n\ndef check(candidate):\n...
68,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",pluck,if(len(arr) == 0): return []\n evens = ...,def check(candidate):\n\n # Check some simp...
69,HumanEval/69,\ndef search(lst):\n '''\n You are given...,search,frq = [0] * (max(lst) + 1)\n for i in l...,def check(candidate):\n\n # manually genera...
70,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,strange_sort_list,"res, switch = [], True\n while lst:\n ...",def check(candidate):\n\n # Check some simp...
82,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",prime_length,l = len(string)\n if l == 0 or l == 1:\...,def check(candidate):\n\n # Check some simp...
88,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",sort_array,return [] if len(array) == 0 else sorted(a...,def check(candidate):\n\n # Check some simp...
95,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",check_dict_case,if len(dict.keys()) == 0:\n return ...,def check(candidate):\n\n # Check some simp...
99,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,closest_integer,"from math import floor, ceil\n\n if val...",def check(candidate):\n\n # Check some simp...
127,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",intersection,def is_prime(num):\n if num == 1 or...,def check(candidate):\n\n # Check some simp...
138,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",is_equal_to_sum_even,return n%2 == 0 and n >= 8\n,def check(candidate):\n assert candidate(4)...
145,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",order_by_points,def digits_sum(n):\n neg = 1\n ...,def check(candidate):\n\n # Check some simp...
153,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",Strongest_Extension,strong = extensions[0]\n my_val = len([...,def check(candidate):\n\n # Check some simp...
156,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",int_to_mini_roman,"num = [1, 4, 5, 9, 10, 40, 50, 90, \n ...",def check(candidate):\n\n # Check some simp...
158,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",find_max,"return sorted(words, key = lambda x: (-len...",def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...

In [141]:
new_solutions_df

,task_id,prompt,completion
0,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,
1,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...","prev_prev = 0\n curr_pprev, curr_prev =..."
2,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",
3,HumanEval/69,\ndef search(lst):\n '''\n You are given...,
4,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,
5,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",
6,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",pass
7,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",
8,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,# your code here\n
9,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",
10,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",if (n % 2 !=0 and not((int)(1/2)*n==n)): #...
11,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",\n
12,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",# your code here\n \n
13,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",\n # Mapping to the numbers from 1-9 wi...
14,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",
15,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",
16,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",# Your code here\n if (b > a):\n ...

In [122]:
df

,task_id,prompt,entry_point,canonical_solution,test
0,HumanEval/0,from typing import List\n\n\ndef has_close_ele...,has_close_elements,"for idx, elem in enumerate(numbers):\n ...","\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
1,HumanEval/1,from typing import List\n\n\ndef separate_pare...,separate_paren_groups,result = []\n current_string = []\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
2,HumanEval/2,\n\ndef truncate_number(number: float) -> floa...,truncate_number,return number % 1.0\n,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
3,HumanEval/3,from typing import List\n\n\ndef below_zero(op...,below_zero,balance = 0\n\n for op in operations:\n...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
4,HumanEval/4,from typing import List\n\n\ndef mean_absolute...,mean_absolute_deviation,mean = sum(numbers) / len(numbers)\n re...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
...,...,...,...,...,...
159,HumanEval/159,"\ndef eat(number, need, remaining):\n """"""\n...",eat,if(need <= remaining):\n return [ n...,def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
161,HumanEval/161,"\ndef solve(s):\n """"""You are given a string...",solve,flg = 0\n idx = 0\n new_str = list(s...,def check(candidate):\n\n # Check some simp...
162,HumanEval/162,"\ndef string_to_md5(text):\n """"""\n Given...",string_to_md5,import hashlib\n return hashlib.md5(tex...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...

In [123]:
failed_ids = new_solutions_df[
    (new_solutions_df['completion'] == False) |
    (new_solutions_df['completion'].isna()) |
    (new_solutions_df['completion'] == '') |
    (new_solutions_df['completion'].astype(str).str.isspace()) |
    (new_solutions_df['completion'].astype(str).str.strip() == '')
]['task_id'].tolist()  # Added ['task_id'] here

failed_questions_df = df[df['task_id'].isin(failed_ids)]
failed_questions_df

,task_id,prompt,entry_point,canonical_solution,test
26,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,remove_duplicates,import collections\n c = collections.Co...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
46,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...",fib4,"results = [0, 0, 2, 0]\n if n < 4:\n ...",\n\nMETADATA = {}\n\n\ndef check(candidate):\n...
68,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",pluck,if(len(arr) == 0): return []\n evens = ...,def check(candidate):\n\n # Check some simp...
69,HumanEval/69,\ndef search(lst):\n '''\n You are given...,search,frq = [0] * (max(lst) + 1)\n for i in l...,def check(candidate):\n\n # manually genera...
70,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,strange_sort_list,"res, switch = [], True\n while lst:\n ...",def check(candidate):\n\n # Check some simp...
82,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",prime_length,l = len(string)\n if l == 0 or l == 1:\...,def check(candidate):\n\n # Check some simp...
88,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",sort_array,return [] if len(array) == 0 else sorted(a...,def check(candidate):\n\n # Check some simp...
95,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",check_dict_case,if len(dict.keys()) == 0:\n return ...,def check(candidate):\n\n # Check some simp...
99,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,closest_integer,"from math import floor, ceil\n\n if val...",def check(candidate):\n\n # Check some simp...
127,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",intersection,def is_prime(num):\n if num == 1 or...,def check(candidate):\n\n # Check some simp...
138,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",is_equal_to_sum_even,return n%2 == 0 and n >= 8\n,def check(candidate):\n assert candidate(4)...
145,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",order_by_points,def digits_sum(n):\n neg = 1\n ...,def check(candidate):\n\n # Check some simp...
153,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",Strongest_Extension,strong = extensions[0]\n my_val = len([...,def check(candidate):\n\n # Check some simp...
156,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",int_to_mini_roman,"num = [1, 4, 5, 9, 10, 40, 50, 90, \n ...",def check(candidate):\n\n # Check some simp...
158,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",find_max,"return sorted(words, key = lambda x: (-len...",def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...

In [143]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/human-eval/humaneval_samples_updated.csv')

# Display the first few rows
df

,passed,completion,result,task_id
0,True,numbers_to_check = sorted(numbers)\n fo...,passed,HumanEval/0
1,False,\n parens = []\n # Stack for keeping tr...,failed:,HumanEval/1
2,True,return number - int(number)\n\n\ndef is_py...,passed,HumanEval/2
3,True,balance = 0\n for operation in operatio...,passed,HumanEval/3
4,True,numbers_mean = sum(numbers) / len(numbers)...,passed,HumanEval/4
...,...,...,...,...
159,False,# TODO - Add Your Code Here - 8 Lines (~3-...,failed: Error,HumanEval/159
160,False,NaN,failed:,HumanEval/160
161,False,\n #for i in range (len(s)): ## Loop ...,failed:,HumanEval/161
162,True,\n import hashlib\n\n if not text:\n ...,passed,HumanEval/162
163,False,,failed: Test 1,HumanEval/163

In [109]:
df

,passed,completion,result,task_id
0,True,numbers_to_check = sorted(numbers)\n fo...,passed,HumanEval/0
1,False,\n parens = []\n # Stack for keeping tr...,failed:,HumanEval/1
2,True,return number - int(number)\n\n\ndef is_py...,passed,HumanEval/2
3,True,balance = 0\n for operation in operatio...,passed,HumanEval/3
4,True,numbers_mean = sum(numbers) / len(numbers)...,passed,HumanEval/4
...,...,...,...,...
159,False,# TODO - Add Your Code Here - 8 Lines (~3-...,failed: Error,HumanEval/159
160,False,NaN,failed:,HumanEval/160
161,False,\n #for i in range (len(s)): ## Loop ...,failed:,HumanEval/161
162,True,\n import hashlib\n\n if not text:\n ...,passed,HumanEval/162
163,False,\n,failed: Test 1,HumanEval/163

In [145]:
failed_ids = df[df['passed'] == False]['task_id']
len(failed_ids)

103

In [146]:
new_solutions_df

,task_id,prompt,completion
0,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,
1,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...","prev_prev = 0\n curr_pprev, curr_prev =..."
2,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",
3,HumanEval/69,\ndef search(lst):\n '''\n You are given...,
4,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,
5,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",
6,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",pass
7,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",
8,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,# your code here\n
9,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",
10,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",if (n % 2 !=0 and not((int)(1/2)*n==n)): #...
11,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",\n
12,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",# your code here\n \n
13,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",\n # Mapping to the numbers from 1-9 wi...
14,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",
15,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",
16,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",# Your code here\n if (b > a):\n ...

In [117]:
failed_ids = df_changed[
    (df_changed['completion'] == False) |
    (df_changed['completion'].isna()) |
    (df_changed['completion'] == '') |
    (df_changed['completion'].astype(str).str.isspace()) |
    (df_changed['completion'].astype(str).str.strip() == '')
]['task_id'].tolist()  # Added ['task_id'] here

failed_questions_df = df[df['task_id'].isin(failed_ids)]
failed_questions_df

,task_id,prompt,entry_point,canonical_solution,test
25,HumanEval/25,from typing import List\n\n\ndef factorize(n: ...,factorize,import math\n fact = []\n i = 2\n ...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
26,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,remove_duplicates,import collections\n c = collections.Co...,"\n\nMETADATA = {\n 'author': 'jt',\n 'da..."
33,HumanEval/33,"\n\ndef sort_third(l: list):\n """"""This func...",sort_third,l = list(l)\n l[::3] = sorted(l[::3])\n...,\n\nMETADATA = {}\n\n\ndef check(candidate):\n...
34,HumanEval/34,"\n\ndef unique(l: list):\n """"""Return sorted...",unique,return sorted(list(set(l)))\n,\n\nMETADATA = {}\n\n\ndef check(candidate):\n...
46,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...",fib4,"results = [0, 0, 2, 0]\n if n < 4:\n ...",\n\nMETADATA = {}\n\n\ndef check(candidate):\n...
64,HumanEval/64,"\nFIX = """"""\nAdd more test cases.\n""""""\n\ndef ...",vowels_count,"vowels = ""aeiouAEIOU""\n n_vowels = sum(...",def check(candidate):\n\n # Check some simp...
68,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",pluck,if(len(arr) == 0): return []\n evens = ...,def check(candidate):\n\n # Check some simp...
69,HumanEval/69,\ndef search(lst):\n '''\n You are given...,search,frq = [0] * (max(lst) + 1)\n for i in l...,def check(candidate):\n\n # manually genera...
70,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,strange_sort_list,"res, switch = [], True\n while lst:\n ...",def check(candidate):\n\n # Check some simp...
78,HumanEval/78,"\ndef hex_key(num):\n """"""You have been task...",hex_key,"primes = ('2', '3', '5', '7', 'B', 'D')\n ...",def check(candidate):\n\n # Check some simp...
82,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",prime_length,l = len(string)\n if l == 0 or l == 1:\...,def check(candidate):\n\n # Check some simp...
88,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",sort_array,return [] if len(array) == 0 else sorted(a...,def check(candidate):\n\n # Check some simp...
93,HumanEval/93,"\ndef encode(message):\n """"""\n Write a f...",encode,"vowels = ""aeiouAEIOU""\n vowels_replace ...",def check(candidate):\n\n # Check some simp...
94,HumanEval/94,"\n\ndef skjkasdkd(lst):\n """"""You are given ...",skjkasdkd,"def isPrime(n):\n for i in range(2,...",def check(candidate):\n\n # Check some simp...
95,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",check_dict_case,if len(dict.keys()) == 0:\n return ...,def check(candidate):\n\n # Check some simp...
98,HumanEval/98,"\ndef count_upper(s):\n """"""\n Given a st...",count_upper,"count = 0\n for i in range(0,len(s),2):...",def check(candidate):\n\n # Check some simp...
99,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,closest_integer,"from math import floor, ceil\n\n if val...",def check(candidate):\n\n # Check some simp...
109,HumanEval/109,"\ndef move_one_ball(arr):\n """"""We have an a...",move_one_ball,if len(arr)==0:\n return True\n so...,def check(candidate):\n\n # Check some simp...
113,HumanEval/113,"\ndef odd_count(lst):\n """"""Given a list of ...",odd_count,res = []\n for arr in lst:\n n =...,def check(candidate):\n\n # Check some simp...
120,HumanEval/120,"\ndef maximum(arr, k):\n """"""\n Given an ...",maximum,if k == 0:\n return []\n arr.sor...,def check(candidate):\n\n # Check some simp...
127,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",intersection,def is_prime(num):\n if num == 1 or...,def check(candidate):\n\n # Check some simp...
129,HumanEval/129,"\ndef minPath(grid, k):\n """"""\n Given a ...",minPath,n = len(grid)\n val = n * n + 1\n fo...,def check(candidate):\n\n # Check some simp...
131,HumanEval/131,"\ndef digits(n):\n """"""Given a positive inte...",digits,product = 1\n odd_count = 0\n for di...,def check(candidate):\n\n # Check some simp...
135,HumanEval/135,"\ndef can_arrange(arr):\n """"""Create a funct...",can_arrange,ind=-1\n i=1\n while i<len(arr):\n ...,def check(candidate):\n\n # Check some simp...
138,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",is_equal_to_sum_even,return n%2 == 0 and n >= 8\n,def check(candidate):\n assert candidate(4)...
145,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",order_by_points,def digits_sum(n):\n neg = 1\n ...,def check(candidate):\n\n # Check some simp...
153,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",Strongest_Extension,strong = extensions[0]\n my_val = len([...,def check(candidate):\n\n # Check some simp...
154,HumanEval/154,"\ndef cycpattern_check(a , b):\n """"""You are...",cycpattern_check,l = len(b)\n pat = b + b\n for i in ...,def check(candidate):\n\n # Check some simp...
156,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",int_to_mini_roman,"num = [1, 4, 5, 9, 10, 40, 50, 90, \n ...",def check(candidate):\n\n # Check some simp...
158,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",find_max,"return sorted(words, key = lambda x: (-len...",def check(candidate):\n\n # Check some simp...
160,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",do_algebra,expression = str(operand[0])\n for oprt...,def check(candidate):\n\n # Check some simp...
163,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",generate_integers,"lower = max(2, min(a, b))\n upper = min...",def check(candidate):\n\n # Check some simp...



ORIGINAL DF!

In [149]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/human-eval/humaneval_samples.csv')

# Display the first few rows
df

                                            completion        task_id
0        numbers_to_check = sorted(numbers)\n    fo...    HumanEval/0
1        groups = []\n    paren_stack = []\n    gro...    HumanEval/1
2        return number - int(number)\n\n\ndef is_py...    HumanEval/2
3        balance = 0\n    for operation in operatio...    HumanEval/3
4        numbers_mean = sum(numbers) / len(numbers)...    HumanEval/4
..                                                 ...            ...
159      if (number < need):\n        return [numbe...  HumanEval/159
160      return sum([int(operand[i])*eval(f"{operat...  HumanEval/160
161      if s.isalpha():\n        return s.swapcase...  HumanEval/161
162  \n    import hashlib\n\n    if not text:\n    ...  HumanEval/162
163      if a > b:\n        return []\n    else:\n ...  HumanEval/163

[164 rows x 2 columns]

In [115]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df_changed = pd.read_csv('/content/human-eval/changed.csv')

# Display the first few rows
df_changed

,passed,completion,result,task_id
0,True,numbers_to_check = sorted(numbers)\n fo...,passed,HumanEval/0
1,False,\n parens = []\n # Stack for keeping tr...,failed:,HumanEval/1
2,True,return number - int(number)\n\n\ndef is_py...,passed,HumanEval/2
3,True,balance = 0\n for operation in operatio...,passed,HumanEval/3
4,True,numbers_mean = sum(numbers) / len(numbers)...,passed,HumanEval/4
...,...,...,...,...
159,False,# TODO - Add Your Code Here - 8 Lines (~3-...,failed: Error,HumanEval/159
160,False,NaN,failed:,HumanEval/160
161,False,\n #for i in range (len(s)): ## Loop ...,failed:,HumanEval/161
162,True,\n import hashlib\n\n if not text:\n ...,passed,HumanEval/162
163,False,\n,failed: Test 1,HumanEval/163

In [135]:
failed_ids = df_changed[df_changed['passed'] == False]['task_id']
len(failed_ids)

103

In [72]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/human-eval/humaneval_samples.jsonl_results-2.csv')

# Display the first few rows
df

,task_id,completion,result,passed
0,HumanEval/0,numbers_to_check = sorted(numbers)\r\n ...,passed,True
1,HumanEval/1,groups = []\r\n paren_stack = []\r\n ...,failed: list index out of range,False
2,HumanEval/2,return number - int(number)\r\n\r\n\r\ndef...,passed,True
3,HumanEval/3,balance = 0\r\n for operation in operat...,passed,True
4,HumanEval/4,numbers_mean = sum(numbers) / len(numbers)...,passed,True
...,...,...,...,...
159,HumanEval/159,if (number < need):\r\n return [num...,failed: Error,False
160,HumanEval/160,"return sum([int(operand[i])*eval(f""{operat...","failed: invalid syntax (<string>, line 1)",False
161,HumanEval/161,if s.isalpha():\r\n return s.swapca...,failed:,False
162,HumanEval/162,\r\n import hashlib\r\n\r\n if not text:...,passed,True
163,HumanEval/163,if a > b:\r\n return []\r\n else...,failed: Test 1,False

In [96]:
import json
import csv
import pandas as pd

# Define file paths
jsonl_file_path = '/content/human-eval/humaneval_samples_updated.jsonl_results.jsonl'
csv_file_path = '/content/human-eval/changed.csv'

# Read the JSONL file and convert to a list of dictionaries
data = []
with open(jsonl_file_path, 'r', encoding='utf-8') as jsonl_file:
    for line in jsonl_file:
        if line.strip():  # Skip empty lines
            data.append(json.loads(line))

# If the file is empty, exit early
if not data:
    print("Input file is empty")
else:
    # Get all unique keys to use as CSV headers
    headers = set()
    for item in data:
        headers.update(item.keys())
    headers = list(headers)

    # Write the data to a CSV file
    with open(csv_file_path, 'w', encoding='utf-8', newline='') as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=headers)
        writer.writeheader()
        writer.writerows(data)

    print(f"Successfully converted {jsonl_file_path} to {csv_file_path}")

    # Display the first few rows of the CSV file to verify
    df = pd.read_csv(csv_file_path)
    display(df)

Successfully converted /content/human-eval/humaneval_samples_updated.jsonl_results.jsonl to /content/human-eval/changed.csv

,passed,completion,result,task_id
0,True,numbers_to_check = sorted(numbers)\n fo...,passed,HumanEval/0
1,False,\n parens = []\n # Stack for keeping tr...,failed:,HumanEval/1
2,True,return number - int(number)\n\n\ndef is_py...,passed,HumanEval/2
3,True,balance = 0\n for operation in operatio...,passed,HumanEval/3
4,True,numbers_mean = sum(numbers) / len(numbers)...,passed,HumanEval/4
...,...,...,...,...
159,False,# TODO - Add Your Code Here - 8 Lines (~3-...,failed: Error,HumanEval/159
160,False,NaN,failed:,HumanEval/160
161,False,\n #for i in range (len(s)): ## Loop ...,failed:,HumanEval/161
162,True,\n import hashlib\n\n if not text:\n ...,passed,HumanEval/162
163,False,\n,failed: Test 1,HumanEval/163

In [126]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/human-eval/changed.csv')

# Display the first few rows
df

,passed,completion,result,task_id
0,True,numbers_to_check = sorted(numbers)\n fo...,passed,HumanEval/0
1,False,\n parens = []\n # Stack for keeping tr...,failed:,HumanEval/1
2,True,return number - int(number)\n\n\ndef is_py...,passed,HumanEval/2
3,True,balance = 0\n for operation in operatio...,passed,HumanEval/3
4,True,numbers_mean = sum(numbers) / len(numbers)...,passed,HumanEval/4
...,...,...,...,...
159,False,# TODO - Add Your Code Here - 8 Lines (~3-...,failed: Error,HumanEval/159
160,False,NaN,failed:,HumanEval/160
161,False,\n #for i in range (len(s)): ## Loop ...,failed:,HumanEval/161
162,True,\n import hashlib\n\n if not text:\n ...,passed,HumanEval/162
163,False,\n,failed: Test 1,HumanEval/163

In [131]:
new_solutions_df

,task_id,prompt,completion
0,HumanEval/25,from typing import List\n\n\ndef factorize(n: ...,"\n assert n > 0 and isinstance(n, (int)..."
1,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,\n
2,HumanEval/33,"\n\ndef sort_third(l: list):\n """"""This func...",\n result = [] # this will be our final...
3,HumanEval/34,"\n\ndef unique(l: list):\n """"""Return sorted...",return sorted({i for i in l})
4,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...",\n
5,HumanEval/64,"\nFIX = """"""\nAdd more test cases.\n""""""\n\ndef ...",pass\n
6,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",NaN
7,HumanEval/69,\ndef search(lst):\n '''\n You are given...,
8,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,
9,HumanEval/78,"\ndef hex_key(num):\n """"""You have been task...",\n # your code goes here\n # HEX_DIG...
10,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",
11,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",\n
12,HumanEval/93,"\ndef encode(message):\n """"""\n Write a f...",pass #TODO
13,HumanEval/94,"\n\ndef skjkasdkd(lst):\n """"""You are given ...",\n import math\n \n # create ...
14,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",
15,HumanEval/98,"\ndef count_upper(s):\n """"""\n Given a st...",# Your code here\n
16,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,NaN
17,HumanEval/109,"\ndef move_one_ball(arr):\n """"""We have an a...",# To find whether a particular value occur...
18,HumanEval/113,"\ndef odd_count(lst):\n """"""Given a list of ...",result = []\n for elem in lst:\n ...
19,HumanEval/120,"\ndef maximum(arr, k):\n """"""\n Given an ...",if not arr or k == 0:\n return []\n...
20,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",NaN
21,HumanEval/129,"\ndef minPath(grid, k):\n """"""\n Given a ...",nRows = len(grid); assert nRows > 0;\n ...
22,HumanEval/131,"\ndef digits(n):\n """"""Given a positive inte...",# Your code here\n total = []\n \n ...
23,HumanEval/135,"\ndef can_arrange(arr):\n """"""Create a funct...",pass
24,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",
25,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",NaN
26,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",
27,HumanEval/154,"\ndef cycpattern_check(a , b):\n """"""You are...","\n#print (cycpattern_check('hi','si'))"
28,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",NaN
29,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",NaN
30,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",NaN
31,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",

In [128]:
new_solutions_df = pd.read_csv('/content/human-eval/regenerated_solutions.csv')
new_solutions_df

,task_id,prompt,completion
0,HumanEval/25,from typing import List\n\n\ndef factorize(n: ...,"\n assert n > 0 and isinstance(n, (int)..."
1,HumanEval/26,from typing import List\n\n\ndef remove_duplic...,\n
2,HumanEval/33,"\n\ndef sort_third(l: list):\n """"""This func...",\n result = [] # this will be our final...
3,HumanEval/34,"\n\ndef unique(l: list):\n """"""Return sorted...",return sorted({i for i in l})
4,HumanEval/46,"\n\ndef fib4(n: int):\n """"""The Fib4 number ...",\n
5,HumanEval/64,"\nFIX = """"""\nAdd more test cases.\n""""""\n\ndef ...",pass\n
6,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",NaN
7,HumanEval/69,\ndef search(lst):\n '''\n You are given...,
8,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,
9,HumanEval/78,"\ndef hex_key(num):\n """"""You have been task...",\n # your code goes here\n # HEX_DIG...
10,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",
11,HumanEval/88,"\ndef sort_array(array):\n """"""\n Given a...",\n
12,HumanEval/93,"\ndef encode(message):\n """"""\n Write a f...",pass #TODO
13,HumanEval/94,"\n\ndef skjkasdkd(lst):\n """"""You are given ...",\n import math\n \n # create ...
14,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",
15,HumanEval/98,"\ndef count_upper(s):\n """"""\n Given a st...",# Your code here\n
16,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,NaN
17,HumanEval/109,"\ndef move_one_ball(arr):\n """"""We have an a...",# To find whether a particular value occur...
18,HumanEval/113,"\ndef odd_count(lst):\n """"""Given a list of ...",result = []\n for elem in lst:\n ...
19,HumanEval/120,"\ndef maximum(arr, k):\n """"""\n Given an ...",if not arr or k == 0:\n return []\n...
20,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",NaN
21,HumanEval/129,"\ndef minPath(grid, k):\n """"""\n Given a ...",nRows = len(grid); assert nRows > 0;\n ...
22,HumanEval/131,"\ndef digits(n):\n """"""Given a positive inte...",# Your code here\n total = []\n \n ...
23,HumanEval/135,"\ndef can_arrange(arr):\n """"""Create a funct...",pass
24,HumanEval/138,"\ndef is_equal_to_sum_even(n):\n """"""Evaluat...",
25,HumanEval/145,"\ndef order_by_points(nums):\n """"""\n Wri...",NaN
26,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",
27,HumanEval/154,"\ndef cycpattern_check(a , b):\n """"""You are...","\n#print (cycpattern_check('hi','si'))"
28,HumanEval/156,"\ndef int_to_mini_roman(number):\n """"""\n ...",NaN
29,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",NaN
30,HumanEval/160,"\ndef do_algebra(operator, operand):\n """"""\...",NaN
31,HumanEval/163,"\ndef generate_integers(a, b):\n """"""\n G...",

In [150]:
df

                                            completion        task_id
0        numbers_to_check = sorted(numbers)\n    fo...    HumanEval/0
1        groups = []\n    paren_stack = []\n    gro...    HumanEval/1
2        return number - int(number)\n\n\ndef is_py...    HumanEval/2
3        balance = 0\n    for operation in operatio...    HumanEval/3
4        numbers_mean = sum(numbers) / len(numbers)...    HumanEval/4
..                                                 ...            ...
159      if (number < need):\n        return [numbe...  HumanEval/159
160      return sum([int(operand[i])*eval(f"{operat...  HumanEval/160
161      if s.isalpha():\n        return s.swapcase...  HumanEval/161
162  \n    import hashlib\n\n    if not text:\n    ...  HumanEval/162
163      if a > b:\n        return []\n    else:\n ...  HumanEval/163

[164 rows x 2 columns]

In [241]:
new_solutions_df

,task_id,prompt,completion
0,HumanEval/25,from typing import List\n\n\ndef factorize(n: ...,\n # Create an empty array for result a...
1,HumanEval/68,"\ndef pluck(arr):\n """"""\n ""Given an arra...",# if not arr:\n # return None\n\n ...
2,HumanEval/70,\ndef strange_sort_list(lst):\n '''\n Gi...,
3,HumanEval/82,"\ndef prime_length(string):\n """"""Write a fu...",
4,HumanEval/95,"\ndef check_dict_case(dict):\n """"""\n Giv...",
5,HumanEval/99,\ndef closest_integer(value):\n '''\n Cr...,# Your code here\n
6,HumanEval/113,"\ndef odd_count(lst):\n """"""Given a list of ...",\n lst2 = [] #...
7,HumanEval/127,"\ndef intersection(interval1, interval2):\n ...",
8,HumanEval/153,"\ndef Strongest_Extension(class_name, extensio...",
9,HumanEval/158,"\ndef find_max(words):\n """"""Write a functio...",max = -1; curr= ''\n \n# for i in ran...

In [256]:
import pandas as pd

# Load both CSV files
# Assuming the files are saved as humaneval_samples.csv (164 rows) and new_solutions_df.csv (109 rows)
original_df = new_df.copy()
print(f"Original dataframe: {len(original_df)} rows")
print(f"New solutions dataframe: {len(new_solutions_df)} rows")

# Create a mapping from task_id to completion in the new solutions dataframe
completion_map = dict(zip(new_solutions_df['task_id'], new_solutions_df['completion']))

# Function to replace completion if task_id exists in the new solutions
def replace_completion(row):
    task_id = row['task_id']
    if task_id in completion_map:
        return completion_map[task_id]
    return row['completion']

# Create a copy of the original dataframe
updated_df = original_df.copy()

# Apply the replacement function
updated_df['completion'] = updated_df.apply(replace_completion, axis=1)

# Count how many completions were replaced
replacements_count = sum(1 for task_id in original_df['task_id'] if task_id in completion_map)
print(f"Replaced {replacements_count} completions in the original dataframe")

# Save the updated dataframe
updated_df.to_csv('/content/human-eval/update5.csv', index=False)
print(f"Updated dataframe saved to '/content/human-eval/update5.csv'")

Original dataframe: 164 rows
New solutions dataframe: 5 rows
Replaced 5 completions in the original dataframe
Updated dataframe saved to '/content/human-eval/update5.csv'

In [243]:
updated_df

,task_id,completion,prompt
0,HumanEval/0,numbers_to_check = sorted(numbers)\n fo...,from typing import List\n\n\ndef has_close_ele...
1,HumanEval/1,\n parens = []\n # Stack for keeping tr...,from typing import List\n\n\ndef separate_pare...
2,HumanEval/2,return number - int(number)\n\n\ndef is_py...,\n\ndef truncate_number(number: float) -> floa...
3,HumanEval/3,balance = 0\n for operation in operatio...,from typing import List\n\n\ndef below_zero(op...
4,HumanEval/4,numbers_mean = sum(numbers) / len(numbers)...,from typing import List\n\n\ndef mean_absolute...
...,...,...,...
159,HumanEval/159,# TODO - Add Your Code Here - 8 Lines (~3-...,"\ndef eat(number, need, remaining):\n """"""\n..."
160,HumanEval/160,op=operator[0]; operand1=operand[0]; opera...,"\ndef do_algebra(operator, operand):\n """"""\..."
161,HumanEval/161,\n #for i in range (len(s)): ## Loop ...,"\ndef solve(s):\n """"""You are given a string..."
162,HumanEval/162,\n import hashlib\n\n if not text:\n ...,"\ndef string_to_md5(text):\n """"""\n Given..."
163,HumanEval/163,if not (type(a) == int or type(b) == int):...,"\ndef generate_integers(a, b):\n """"""\n G..."

In [257]:
# updated_df = pd.read_csv('/content/human-eval/humaneval_samples_updated.csv')

updated_df = updated_df[['task_id', 'completion']]
updated_df

           task_id                                         completion
0      HumanEval/0      numbers_to_check = sorted(numbers)\n    fo...
1      HumanEval/1  \n    parens = []\n     # Stack for keeping tr...
2      HumanEval/2      return number - int(number)\n\n\ndef is_py...
3      HumanEval/3      balance = 0\n    for operation in operatio...
4      HumanEval/4      numbers_mean = sum(numbers) / len(numbers)...
..             ...                                                ...
159  HumanEval/159      # TODO - Add Your Code Here - 8 Lines (~3-...
160  HumanEval/160      op=operator[0]; operand1=operand[0]; opera...
161  HumanEval/161      \n    #for i in range (len(s)):   ## Loop ...
162  HumanEval/162  \n    import hashlib\n\n    if not text:\n    ...
163  HumanEval/163      if not (type(a) == int or type(b) == int):...

[164 rows x 2 columns]

In [258]:
import csv
import json

# Define file paths
csv_file_path = '/content/human-eval/update5.csv'
jsonl_file_path = '/content/human-eval/update5.jsonl'

# Read the CSV file and convert to a list of dictionaries
data = []
with open(csv_file_path, 'r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        data.append(row)

# Write the data to a JSONL file
with open(jsonl_file_path, 'w', encoding='utf-8') as jsonl_file:
    for item in data:
        # Convert each row to a JSON string and write to file
        jsonl_file.write(json.dumps(item) + '\n')

print(f"Successfully converted {csv_file_path} to {jsonl_file_path}")

# Display some statistics
print(f"Converted {len(data)} records from CSV to JSONL")

Successfully converted /content/human-eval/update5.csv to /content/human-eval/update5.jsonl
Converted 164 records from CSV to JSONL

In [261]:
!python3 results.py /content/human-eval/update5.jsonl_results.jsonl

Reading results from: /content/human-eval/update5.jsonl_results.jsonl

===== RESULTS SUMMARY =====
Total problems: 164
Passed: 62
Failed: 102
Pass rate: 37.80%

===== DETAILED RESULTS =====
HumanEval/0: ✓ PASSED
HumanEval/1: ✗ FAILED
HumanEval/2: ✓ PASSED
HumanEval/3: ✓ PASSED
HumanEval/4: ✓ PASSED
HumanEval/5: ✗ FAILED
   Error: assignment expression cannot rebind comprehension iteration variable 'i' (<string>, line 14)
HumanEval/6: ✗ FAILED
HumanEval/7: ✓ PASSED
HumanEval/8: ✓ PASSED
HumanEval/9: ✓ PASSED
HumanEval/10: ✗ FAILED
HumanEval/11: ✓ PASSED
HumanEval/12: ✗ FAILED
   Error: maximum recursion depth exceeded while calling a Python object
HumanEval/13: ✓ PASSED
HumanEval/14: ✓ PASSED
HumanEval/15: ✓ PASSED
HumanEval/16: ✓ PASSED
HumanEval/17: ✓ PASSED
HumanEval/18: ✓ PASSED
HumanEval/19: ✗ FAILED
   Error: closing parenthesis ')' does not match opening parenthesis '[' (<string>, line 22)
HumanEval/20: ✓ PASSED
HumanEval/21: ✓ PASSED
HumanEval/22: ✓ PASSED
HumanEval/23: ✓ PASSED
HumanEval/24: ✗ FAILED
HumanEval/25: ✗ FAILED
   Error: 4 cannot be factored
HumanEval/26: ✗ FAILED
   Error: unexpected indent (<string>, line 30)
HumanEval/27: ✓ PASSED
HumanEval/28: ✓ PASSED
HumanEval/29: ✗ FAILED
HumanEval/30: ✓ PASSED
HumanEval/31: ✓ PASSED
HumanEval/32: ✗ FAILED
HumanEval/33: ✗ FAILED
   Error: 'NoneType' object is not iterable
HumanEval/34: ✓ PASSED
HumanEval/35: ✓ PASSED
HumanEval/36: ✗ FAILED
HumanEval/37: ✗ FAILED
HumanEval/38: ✗ FAILED
   Error: invalid syntax (<string>, line 41)
HumanEval/39: ✗ FAILED
   Error: name 'primes' is not defined
HumanEval/40: ✗ FAILED
   Error: list index out of range
HumanEval/41: ✗ FAILED
   Error: 0
HumanEval/42: ✓ PASSED
HumanEval/43: ✓ PASSED
HumanEval/44: ✓ PASSED
HumanEval/45: ✓ PASSED
HumanEval/46: ✗ FAILED
   Error: name 'math' is not defined
HumanEval/47: ✓ PASSED
HumanEval/48: ✓ PASSED
HumanEval/49: ✓ PASSED
HumanEval/50: ✓ PASSED
HumanEval/51: ✓ PASSED
HumanEval/52: ✓ PASSED
HumanEval/53: ✓ PASSED
HumanEval/54: ✓ PASSED
HumanEval/55: ✓ PASSED
HumanEval/56: ✓ PASSED
HumanEval/57: ✓ PASSED
HumanEval/58: ✓ PASSED
HumanEval/59: ✗ FAILED
HumanEval/60: ✓ PASSED
HumanEval/61: ✗ FAILED
   Error: cannot assign to subscript here. Maybe you meant '==' instead of '='? (<string>, line 34)
HumanEval/62: ✓ PASSED
HumanEval/63: ✗ FAILED
HumanEval/64: ✗ FAILED
   Error: Test 1
HumanEval/65: ✗ FAILED
   Error: closing parenthesis ']' does not match opening parenthesis '(' on line 27 (<string>, line 31)
HumanEval/66: ✗ FAILED
   Error: Error
HumanEval/67: ✗ FAILED
   Error: invalid literal for int() with base 10: ''
HumanEval/68: ✗ FAILED
   Error: Error
HumanEval/69: ✗ FAILED
   Error: 5
HumanEval/70: ✗ FAILED
HumanEval/71: ✗ FAILED
HumanEval/72: ✓ PASSED
HumanEval/73: ✓ PASSED
HumanEval/74: ✓ PASSED
HumanEval/75: ✗ FAILED
   Error: timed out
HumanEval/76: ✗ FAILED
   Error: expected an indented block after 'else' statement on line 22 (<string>, line 27)
HumanEval/77: ✗ FAILED
   Error: unsupported operand type(s) for /: 'int' and 'type'
HumanEval/78: ✗ FAILED
   Error: object of type 'builtin_function_or_method' has no len()
HumanEval/79: ✓ PASSED
HumanEval/80: ✗ FAILED
   Error: a
HumanEval/81: ✗ FAILED
HumanEval/82: ✗ FAILED
HumanEval/83: ✗ FAILED
   Error: can only concatenate str (not "int") to str
HumanEval/84: ✗ FAILED
   Error: unsupported operand type(s) for +: 'NoneType' and 'str'
HumanEval/85: ✗ FAILED
HumanEval/86: ✗ FAILED
   Error: sequence item 0: expected str instance, list found
HumanEval/87: ✗ FAILED
HumanEval/88: ✗ FAILED
   Error: Error
HumanEval/89: ✗ FAILED
   Error: chr() arg not in range(0x110000)
HumanEval/90: ✗ FAILED
HumanEval/91: ✗ FAILED
   Error: Test 1
HumanEval/92: ✗ FAILED
   Error: unindent does not match any outer indentation level (<string>, line 22)
HumanEval/93: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/94: ✗ FAILED
   Error: invalid syntax (<string>, line 24)
HumanEval/95: ✗ FAILED
   Error: First test error: None
HumanEval/96: ✗ FAILED
HumanEval/97: ✓ PASSED
HumanEval/98: ✗ FAILED
HumanEval/99: ✗ FAILED
   Error: Test 1
HumanEval/100: ✗ FAILED
   Error: name 'math' is not defined
HumanEval/101: ✓ PASSED
HumanEval/102: ✓ PASSED
HumanEval/103: ✓ PASSED
HumanEval/104: ✓ PASSED
HumanEval/105: ✗ FAILED
   Error: Error
HumanEval/106: ✗ FAILED
HumanEval/107: ✓ PASSED
HumanEval/108: ✗ FAILED
HumanEval/109: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/110: ✗ FAILED
HumanEval/111: ✗ FAILED
   Error: name 're' is not defined
HumanEval/112: ✓ PASSED
HumanEval/113: ✗ FAILED
   Error: Test 1
HumanEval/114: ✗ FAILED
   Error: minSubArraySum() missing 1 required positional argument: 'nums'
HumanEval/115: ✗ FAILED
   Error: timed out
HumanEval/116: ✓ PASSED
HumanEval/117: ✗ FAILED
   Error: First test error: None
HumanEval/118: ✗ FAILED
   Error: timed out
HumanEval/119: ✗ FAILED
HumanEval/120: ✗ FAILED
   Error: name 'random' is not defined
HumanEval/121: ✓ PASSED
HumanEval/122: ✗ FAILED
   Error: 'int' object is not iterable
HumanEval/123: ✗ FAILED
   Error: closing parenthesis ')' does not match opening parenthesis '[' (<string>, line 33)
HumanEval/124: ✗ FAILED
HumanEval/125: ✗ FAILED
   Error: '>=' not supported between instances of 'int' and 'str'
HumanEval/126: ✗ FAILED
HumanEval/127: ✗ FAILED
HumanEval/128: ✗ FAILED
   Error: object of type 'type' has no len()
HumanEval/129: ✗ FAILED
   Error: inconsistent use of tabs and spaces in indentation (<string>, line 47)
HumanEval/130: ✗ FAILED
   Error: 'return' outside function (<string>, line 22)
HumanEval/131: ✗ FAILED
HumanEval/132: ✗ FAILED
HumanEval/133: ✗ FAILED
   Error: unindent does not match any outer indentation level (<string>, line 21)
HumanEval/134: ✗ FAILED
   Error: unindent does not match any outer indentation level (<string>, line 32)
HumanEval/135: ✗ FAILED
   Error: cannot access local variable 'ndx' where it is not associated with a value
HumanEval/136: ✓ PASSED
HumanEval/137: ✗ FAILED
   Error: unsupported operand type(s) for -: 'str' and 'float'
HumanEval/138: ✗ FAILED
   Error: invalid syntax (<string>, line 10)
HumanEval/139: ✗ FAILED
   Error: Missing parentheses in call to 'print'. Did you mean print(...)? (<string>, line 21)
HumanEval/140: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/141: ✗ FAILED
HumanEval/142: ✗ FAILED
HumanEval/143: ✓ PASSED
HumanEval/144: ✗ FAILED
   Error: test2
HumanEval/145: ✗ FAILED
HumanEval/146: ✗ FAILED
   Error: specialFilter() missing 1 required positional argument: 'nums'
HumanEval/147: ✓ PASSED
HumanEval/148: ✗ FAILED
   Error: bf() missing 2 required positional arguments: 'planet1' and 'planet2'
HumanEval/149: ✗ FAILED
HumanEval/150: ✗ FAILED
HumanEval/151: ✓ PASSED
HumanEval/152: ✓ PASSED
HumanEval/153: ✗ FAILED
HumanEval/154: ✗ FAILED
   Error: test #0
HumanEval/155: ✗ FAILED
   Error: even_odd_count() missing 1 required positional argument: 'num'
HumanEval/156: ✗ FAILED
   Error: expected ':' (<string>, line 82)
HumanEval/157: ✓ PASSED
HumanEval/158: ✗ FAILED
   Error: unsupported operand type(s) for %: 'NoneType' and 'tuple'
HumanEval/159: ✗ FAILED
   Error: Error
HumanEval/160: ✗ FAILED
   Error: pop from empty list
HumanEval/161: ✗ FAILED
HumanEval/162: ✓ PASSED
HumanEval/163: ✗ FAILED
   Error: unterminated string literal (detected at line 26) (<string>, line 26)

In [259]:
!evaluate_functional_correctness update5.jsonl

Reading samples...
164it [00:00, 5303.47it/s]
Running test suites...
100% 164/164 [00:04<00:00, 38.99it/s]
Writing results to update5.jsonl_results.jsonl...
100% 164/164 [00:00<00:00, 37631.48it/s]
{'pass@1': 0.3780487804878049}

In [262]:
!pwd

/content/human-eval

In [265]:
%cd /content/human-eval
!pwd

/content/human-eval
/content/human-eval

In [29]:
!zip -r directory_contents.zip .

  adding: model_completions.jsonl_results.jsonl (deflated 85%)
  adding: data/ (stored 0%)
  adding: data/example_samples.jsonl (deflated 66%)
  adding: data/example_problem.jsonl (deflated 29%)
  adding: data/HumanEval.jsonl.gz (deflated 0%)
  adding: README.md (deflated 51%)
  adding: update5.csv (deflated 70%)
  adding: humaneval_samples2.jsonl_results.jsonl (deflated 91%)
  adding: human_eval.egg-info/ (stored 0%)
  adding: human_eval.egg-info/PKG-INFO (deflated 24%)
  adding: human_eval.egg-info/SOURCES.txt (deflated 57%)
  adding: human_eval.egg-info/dependency_links.txt (stored 0%)
  adding: human_eval.egg-info/top_level.txt (deflated 18%)
  adding: human_eval.egg-info/requires.txt (stored 0%)
  adding: human_eval.egg-info/entry_points.txt (deflated 31%)
  adding: model_completions.jsonl (deflated 85%)
  adding: setup.py (deflated 49%)
  adding: results.py (deflated 57%)
  adding: update5_with_combined_prompts.csv (deflated 74%)
  adding: humaneval_samples1.jsonl_results.jsonl (deflated 87%)
  adding: LICENSE (deflated 41%)
  adding: human_eval/ (stored 0%)
  adding: human_eval/__pycache__/ (stored 0%)
  adding: human_eval/__pycache__/data.cpython-311.pyc (deflated 54%)
  adding: human_eval/__pycache__/evaluate_functional_correctness.cpython-311.pyc (deflated 40%)
  adding: human_eval/__pycache__/__init__.cpython-311.pyc (deflated 28%)
  adding: human_eval/__pycache__/evaluation.cpython-311.pyc (deflated 49%)
  adding: human_eval/__pycache__/execution.cpython-311.pyc (deflated 54%)
  adding: human_eval/evaluate_functional_correctness.py (deflated 48%)
  adding: human_eval/data.py (deflated 63%)
  adding: human_eval/execution.py (deflated 66%)
  adding: human_eval/evaluation.py (deflated 63%)
  adding: human_eval/__init__.py (stored 0%)
  adding: .git/ (stored 0%)
  adding: .git/packed-refs (deflated 27%)
  adding: .git/description (deflated 14%)
  adding: .git/refs/ (stored 0%)
  adding: .git/refs/heads/ (stored 0%)
  adding: .git/refs/heads/master (stored 0%)
  adding: .git/refs/tags/ (stored 0%)
  adding: .git/refs/remotes/ (stored 0%)
  adding: .git/refs/remotes/origin/ (stored 0%)
  adding: .git/refs/remotes/origin/HEAD (stored 0%)
  adding: .git/index (deflated 43%)
  adding: .git/config (deflated 34%)
  adding: .git/hooks/ (stored 0%)
  adding: .git/hooks/pre-rebase.sample (deflated 59%)
  adding: .git/hooks/pre-applypatch.sample (deflated 38%)
  adding: .git/hooks/push-to-checkout.sample (deflated 55%)
  adding: .git/hooks/pre-receive.sample (deflated 40%)
  adding: .git/hooks/update.sample (deflated 68%)
  adding: .git/hooks/post-update.sample (deflated 27%)
  adding: .git/hooks/prepare-commit-msg.sample (deflated 50%)
  adding: .git/hooks/pre-commit.sample (deflated 45%)
  adding: .git/hooks/pre-push.sample (deflated 49%)
  adding: .git/hooks/pre-merge-commit.sample (deflated 39%)
  adding: .git/hooks/commit-msg.sample (deflated 44%)
  adding: .git/hooks/applypatch-msg.sample (deflated 42%)
  adding: .git/hooks/fsmonitor-watchman.sample (deflated 62%)
  adding: .git/branches/ (stored 0%)
  adding: .git/info/ (stored 0%)
  adding: .git/info/exclude (deflated 28%)
  adding: .git/objects/ (stored 0%)
  adding: .git/objects/pack/ (stored 0%)
  adding: .git/objects/pack/pack-13a5b5e01b84b29437b0fd110026c269c7981830.pack (deflated 0%)
  adding: .git/objects/pack/pack-13a5b5e01b84b29437b0fd110026c269c7981830.idx (deflated 45%)
  adding: .git/objects/info/ (stored 0%)
  adding: .git/logs/ (stored 0%)
  adding: .git/logs/refs/ (stored 0%)
  adding: .git/logs/refs/heads/ (stored 0%)
  adding: .git/logs/refs/heads/master (deflated 28%)
  adding: .git/logs/refs/remotes/ (stored 0%)
  adding: .git/logs/refs/remotes/origin/ (stored 0%)
  adding: .git/logs/refs/remotes/origin/HEAD (deflated 28%)
  adding: .git/logs/HEAD (deflated 28%)
  adding: .git/HEAD (stored 0%)
  adding: humaneval_samples2.jsonl (deflated 91%)
  adding: humaneval_samples1.jsonl (deflated 86%)
  adding: model_completions.csv (deflated 83%)
  adding: requirements.txt (stored 0%)

GENERATED CODE, OG PROMPT, CT PROMPT

In [1]:
import pandas as pd

df = pd.read_csv('/content/update5.csv')
df

,task_id,completion,prompt
0,HumanEval/0,numbers_to_check = sorted(numbers)\n fo...,from typing import List\n\n\ndef has_close_ele...
1,HumanEval/1,\n parens = []\n # Stack for keeping tr...,from typing import List\n\n\ndef separate_pare...
2,HumanEval/2,return number - int(number)\n\n\ndef is_py...,\n\ndef truncate_number(number: float) -> floa...
3,HumanEval/3,balance = 0\n for operation in operatio...,from typing import List\n\n\ndef below_zero(op...
4,HumanEval/4,numbers_mean = sum(numbers) / len(numbers)...,from typing import List\n\n\ndef mean_absolute...
...,...,...,...
159,HumanEval/159,# TODO - Add Your Code Here - 8 Lines (~3-...,"\ndef eat(number, need, remaining):\n """"""\n..."
160,HumanEval/160,op=operator[0]; operand1=operand[0]; opera...,"\ndef do_algebra(operator, operand):\n """"""\..."
161,HumanEval/161,\n #for i in range (len(s)): ## Loop ...,"\ndef solve(s):\n """"""You are given a string..."
162,HumanEval/162,\n import hashlib\n\n if not text:\n ...,"\ndef string_to_md5(text):\n """"""\n Given..."
163,HumanEval/163,if not (type(a) == int or type(b) == int):...,"\ndef generate_integers(a, b):\n """"""\n G..."

In [2]:
import pandas as pd

# Read the existing CSV file
df = pd.read_csv('/content/update5.csv')

# Get the CTPROMPT value from your variable
# From your screenshot, it appears to be defined as: CTPROMPT = ""
# You should replace this with the actual value from your environment
CTPROMPT = "There might be an error in the code below because of lack of understanding of the question. Please correct the error, if any, and rewrite the solution. Only output the final correct Python program! \n"  # Replace with your actual CTPROMPT value

# Print information about the DataFrame
print(f"DataFrame shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
print(f"Using CTPROMPT value: '{CTPROMPT}'")

# Create a new combined prompt column
df['combined_prompt'] = df.apply(
    lambda row: CTPROMPT + str(row['prompt']) + str(row['completion']),
    axis=1
)

# # Show the first few rows to verify
# print("\nFirst few rows with combined prompt:")
# sample_columns = ['task_id', 'combined_prompt']
# pd.set_option('display.max_colwidth', 80)  # Limit display width for readability
# print(df[sample_columns].head())

# # Save the updated DataFrame
# output_file = '/content/human-eval/update5_with_combined_prompts.csv'
# df.to_csv(output_file, index=False)
# print(f"\nSaved updated DataFrame to: {output_file}")

# # If you want to create a new DataFrame with just specific columns
# # For example, if you only need task_id and the combined prompt
# selected_columns = ['task_id', 'combined_prompt']
# new_df = df[selected_columns]

# # Save the new DataFrame
# new_output_file = '/content/human-eval/task_id_with_combined_prompts.csv'
# new_df.to_csv(new_output_file, index=False)
# print(f"Also saved simplified version with just {', '.join(selected_columns)} to: {new_output_file}")

# # Print a more detailed example of one combined prompt
# print("\nDetailed example for first row:")
# first_row = df.iloc[0]
# print(f"Task ID: {first_row['task_id']}")
# print(f"CTPROMPT component: '{CTPROMPT}'")
# print(f"Completion component: '{first_row['completion'][:50]}...'")
# print(f"Prompt component: '{first_row['prompt'][:50]}...'")
# print(f"Combined result: '{first_row['combined_prompt'][:100]}...'")

DataFrame shape: (164, 3)
Columns: ['task_id', 'completion', 'prompt']
Using CTPROMPT value: 'There might be an error in the code below because of lack of understanding of the question. Please correct the error, if any, and rewrite the solution. Only output the final correct Python program!
'

In [5]:
df = df[['task_id', 'combined_prompt']]
output_file = '/content/update5_with_combined_prompts.csv'
df.to_csv(output_file, index=False)

In [5]:
import pandas as pd

# Read the existing CSV file
df = pd.read_csv('/content/human-eval/update5_with_combined_prompts.csv')
df

           task_id                                    combined_prompt
0      HumanEval/0  There might be an error in the code below beca...
1      HumanEval/1  There might be an error in the code below beca...
2      HumanEval/2  There might be an error in the code below beca...
3      HumanEval/3  There might be an error in the code below beca...
4      HumanEval/4  There might be an error in the code below beca...
..             ...                                                ...
159  HumanEval/159  There might be an error in the code below beca...
160  HumanEval/160  There might be an error in the code below beca...
161  HumanEval/161  There might be an error in the code below beca...
162  HumanEval/162  There might be an error in the code below beca...
163  HumanEval/163  There might be an error in the code below beca...

[164 rows x 2 columns]

In [ ]:
inputs = tokenizer(prompt2, return_tensors="pt",
      padding=True,
      return_attention_mask=True).to(model.device)
with torch.no_grad():
    outputs = model.generate(
        input_ids=inputs.input_ids,
        attention_mask=inputs.attention_mask,
        max_new_tokens=1024,
        temperature=0.7,
        top_p=0.95,
        do_sample=True,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
    )

In [ ]:
model_name = "meta-llama/CodeLlama-7b-Python-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    load_in_4bit=True,
    torch_dtype=torch.float16
)

In [8]:
from human_eval.data import read_problems, write_jsonl
import itertools
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm

# Step 1: Load the HumanEval problems
problems = read_problems()

# Step 2: Get the first 10 problem IDs
first_10_keys = list(itertools.islice(problems.keys(), 5))

# Step 3: Load your model and tokenizer
model_name = "meta-llama/CodeLlama-7b-Python-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    load_in_4bit=True,
    torch_dtype=torch.float16
)
model.to("cuda" if torch.cuda.is_available() else "cpu")

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear4bit(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((4096,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)

In [ ]:
from human_eval.data import read_problems, write_jsonl
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from tqdm import tqdm
import pandas as pd
import gc

model_name = "meta-llama/CodeLlama-7b-Python-hf"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.float16,
    )

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
        # Set pad token to a different token than eos_token to avoid warning
        tokenizer.pad_token = "[PAD]"
        # Add this token to the vocabulary
        tokenizer.add_special_tokens({"pad_token": "[PAD]"})

# Update token embeddings to account for any added tokens
model.resize_token_embeddings(len(tokenizer))

In [14]:
df_subset = df.head(5)
df_subset

       task_id                                    combined_prompt
0  HumanEval/0  There might be an error in the code below beca...
1  HumanEval/1  There might be an error in the code below beca...
2  HumanEval/2  There might be an error in the code below beca...
3  HumanEval/3  There might be an error in the code below beca...
4  HumanEval/4  There might be an error in the code below beca...

In [17]:
prompt_column = 'combined_prompt'

samples = []

# Set batch size (adjust based on your GPU memory)
batch_size = 1  # Start with 1 and increase if memory allows

# Process dataframe in batches to improve efficiency
for i in tqdm(range(0, len(df), batch_size), desc="Processing batches"):
    batch_df = df.iloc[i:i+batch_size]

    for _, row in batch_df.iterrows():
        problem_id = row['task_id']
        prompt = row[prompt_column]

        # Skip if prompt is missing
        if pd.isna(prompt):
            print(f"Warning: Prompt is NaN for task {problem_id}, skipping")
            continue

        # Convert prompt to string if it's not already
        prompt = str(prompt)

        # Print the prompt for the first few samples (debugging)
        if i < 2:
            print(f"\nTask ID: {problem_id}")
            print(f"Prompt (first 100 chars): {prompt[:100]}...")

        # Tokenize the prompt
        inputs = tokenizer(prompt, return_tensors="pt", padding=True, return_attention_mask=True).to(model.device)

        # Generate text
        with torch.no_grad():
            outputs = model.generate(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                max_new_tokens=1024,
                temperature=0.7,
                top_p=0.95,
                do_sample=True,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )

        # Decode the generated text
        generated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Extract just the completion part (everything after the prompt)
        completion = generated_code[len(prompt):]

        # Add the result to our samples
        samples.append({
            "task_id": problem_id,
            "completion": completion
        })

    # Clear CUDA cache periodically to avoid OOM errors
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        gc.collect()

# Write results to a JSONL file
output_file = '/content/human-eval/model_completions.jsonl'
write_jsonl(output_file, samples)
print(f"\nWrote {len(samples)} samples to {output_file}")

# Also save as CSV for easier inspection
output_csv = '/content/human-eval/model_completions.csv'
pd.DataFrame(samples).to_csv(output_csv, index=False)
print(f"Also saved results as CSV to {output_csv}")

# Display a few examples of the results
print("\nSample completions:")
for i, sample in enumerate(samples[:2]):  # Show first 2 samples
    print(f"\nTask ID: {sample['task_id']}")
    print(f"Completion (first 200 chars): {sample['completion'][:200]}...")

Processing batches:   0%|          | 0/164 [00:00<?, ?it/s]

Task ID: HumanEval/0
Prompt (first 100 chars): There might be an error in the code below because of lack of understanding of the question. Please c...

Processing batches:   1%|          | 1/164 [00:00<01:16,  2.14it/s]

Task ID: HumanEval/1
Prompt (first 100 chars): There might be an error in the code below because of lack of understanding of the question. Please c...

Processing batches: 100%|██████████| 164/164 [50:14<00:00, 18.38s/it]

Wrote 164 samples to /content/human-eval/model_completions.jsonl
Also saved results as CSV to /content/human-eval/model_completions.csv

Sample completions:

Task ID: HumanEval/0
Completion (first 200 chars): ...

Task ID: HumanEval/1
Completion (first 200 chars):

if __name__ == "__main__":
    import doctest
    doctest.testmod()

    print(separate_paren_groups("( ) (( )) (( )( ))"))
...

In [18]:
!evaluate_functional_correctness model_completions.jsonl

Reading samples...
164it [00:00, 4277.08it/s]
Running test suites...
100% 164/164 [00:01<00:00, 122.32it/s]
Writing results to model_completions.jsonl_results.jsonl...
100% 164/164 [00:00<00:00, 43134.50it/s]
{'pass@1': 0.012195121951219513}

In [22]:
!python3 results.py /content/human-eval/model_completions.jsonl_results.jsonl

Reading results from: /content/human-eval/model_completions.jsonl_results.jsonl

===== RESULTS SUMMARY =====
Total problems: 164
Passed: 2
Failed: 162
Pass rate: 1.22%

===== DETAILED RESULTS =====
HumanEval/0: ✗ FAILED
HumanEval/1: ✗ FAILED
HumanEval/2: ✗ FAILED
HumanEval/3: ✗ FAILED
HumanEval/4: ✗ FAILED
   Error: unsupported operand type(s) for -: 'NoneType' and 'float'
HumanEval/5: ✗ FAILED
HumanEval/6: ✗ FAILED
   Error: unexpected indent (<string>, line 13)
HumanEval/7: ✗ FAILED
HumanEval/8: ✗ FAILED
HumanEval/9: ✗ FAILED
HumanEval/10: ✗ FAILED
   Error: '[' was never closed (<string>, line 128)
HumanEval/11: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 83) (<string>, line 67)
HumanEval/12: ✗ FAILED
   Error: '[' was never closed (<string>, line 42)
HumanEval/13: ✗ FAILED
HumanEval/14: ✗ FAILED
HumanEval/15: ✗ FAILED
   Error: expected ':' (<string>, line 124)
HumanEval/16: ✗ FAILED
HumanEval/17: ✗ FAILED
HumanEval/18: ✗ FAILED
HumanEval/19: ✗ FAILED
HumanEval/20: ✗ FAILED
HumanEval/21: ✗ FAILED
HumanEval/22: ✗ FAILED
HumanEval/23: ✗ FAILED
HumanEval/24: ✗ FAILED
   Error: expected ':' (<string>, line 153)
HumanEval/25: ✗ FAILED
HumanEval/26: ✗ FAILED
   Error: '[' was never closed (<string>, line 19)
HumanEval/27: ✗ FAILED
HumanEval/28: ✗ FAILED
HumanEval/29: ✗ FAILED
HumanEval/30: ✗ FAILED
HumanEval/31: ✗ FAILED
HumanEval/32: ✗ FAILED
   Error: expected an indented block after function definition on line 193 (<string>, line 196)
HumanEval/33: ✗ FAILED
HumanEval/34: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 95) (<string>, line 84)
HumanEval/35: ✗ FAILED
HumanEval/36: ✗ FAILED
   Error: name 'count' is not defined
HumanEval/37: ✗ FAILED
   Error: 'NoneType' object is not iterable
HumanEval/38: ✗ FAILED
   Error: unexpected indent (<string>, line 22)
HumanEval/39: ✗ FAILED
HumanEval/40: ✗ FAILED
HumanEval/41: ✗ FAILED
   Error: 0
HumanEval/42: ✗ FAILED
HumanEval/43: ✗ FAILED
HumanEval/44: ✗ FAILED
HumanEval/45: ✗ FAILED
HumanEval/46: ✗ FAILED
   Error: invalid syntax (<string>, line 90)
HumanEval/47: ✗ FAILED
HumanEval/48: ✗ FAILED
HumanEval/49: ✗ FAILED
HumanEval/50: ✗ FAILED
   Error: name 'MORSE' is not defined
HumanEval/51: ✗ FAILED
HumanEval/52: ✗ FAILED
HumanEval/53: ✗ FAILED
HumanEval/54: ✗ FAILED
HumanEval/55: ✗ FAILED
HumanEval/56: ✗ FAILED
HumanEval/57: ✗ FAILED
HumanEval/58: ✗ FAILED
HumanEval/59: ✗ FAILED
   Error: expected ':' (<string>, line 123)
HumanEval/60: ✗ FAILED
HumanEval/61: ✗ FAILED
HumanEval/62: ✗ FAILED
HumanEval/63: ✓ PASSED
HumanEval/64: ✗ FAILED
   Error: Test 1
HumanEval/65: ✗ FAILED
HumanEval/66: ✓ PASSED
HumanEval/67: ✗ FAILED
HumanEval/68: ✗ FAILED
   Error: Error
HumanEval/69: ✗ FAILED
HumanEval/70: ✗ FAILED
   Error: invalid syntax (<string>, line 13)
HumanEval/71: ✗ FAILED
HumanEval/72: ✗ FAILED
HumanEval/73: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 114) (<string>, line 96)
HumanEval/74: ✗ FAILED
HumanEval/75: ✗ FAILED
HumanEval/76: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/77: ✗ FAILED
   Error: First test error: None
HumanEval/78: ✗ FAILED
   Error: First test error: None
HumanEval/79: ✗ FAILED
HumanEval/80: ✗ FAILED
   Error: a
HumanEval/81: ✗ FAILED
HumanEval/82: ✗ FAILED
HumanEval/83: ✗ FAILED
   Error: name 'result' is not defined
HumanEval/84: ✗ FAILED
   Error: Error
HumanEval/85: ✗ FAILED
HumanEval/86: ✗ FAILED
HumanEval/87: ✗ FAILED
HumanEval/88: ✗ FAILED
   Error: Error
HumanEval/89: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/90: ✗ FAILED
HumanEval/91: ✗ FAILED
   Error: Test 3
HumanEval/92: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/93: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/94: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/95: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 98) (<string>, line 76)
HumanEval/96: ✗ FAILED
   Error: name 'result' is not defined
HumanEval/97: ✗ FAILED
   Error: First test error: None
HumanEval/98: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 102) (<string>, line 82)
HumanEval/99: ✗ FAILED
   Error: Test 2
HumanEval/100: ✗ FAILED
   Error: invalid syntax (<string>, line 16)
HumanEval/101: ✗ FAILED
HumanEval/102: ✗ FAILED
HumanEval/103: ✗ FAILED
HumanEval/104: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 132) (<string>, line 118)
HumanEval/105: ✗ FAILED
   Error: Error
HumanEval/106: ✗ FAILED
HumanEval/107: ✗ FAILED
HumanEval/108: ✗ FAILED
   Error: invalid syntax (<string>, line 12)
HumanEval/109: ✗ FAILED
HumanEval/110: ✗ FAILED
HumanEval/111: ✗ FAILED
   Error: name 'hist' is not defined
HumanEval/112: ✗ FAILED
HumanEval/113: ✗ FAILED
   Error: Test 1
HumanEval/114: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/115: ✗ FAILED
   Error: No module named 'solution'
HumanEval/116: ✗ FAILED
HumanEval/117: ✗ FAILED
   Error: First test error: None
HumanEval/118: ✗ FAILED
HumanEval/119: ✗ FAILED
HumanEval/120: ✗ FAILED
HumanEval/121: ✗ FAILED
HumanEval/122: ✗ FAILED
HumanEval/123: ✗ FAILED
HumanEval/124: ✗ FAILED
HumanEval/125: ✗ FAILED
   Error: invalid syntax (<string>, line 13)
HumanEval/126: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 116) (<string>, line 83)
HumanEval/127: ✗ FAILED
HumanEval/128: ✗ FAILED
   Error: unexpected indent (<string>, line 15)
HumanEval/129: ✗ FAILED
   Error: Missing parentheses in call to 'print'. Did you mean print(...)? (<string>, line 38)
HumanEval/130: ✗ FAILED
HumanEval/131: ✗ FAILED
   Error: '(' was never closed (<string>, line 105)
HumanEval/132: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/133: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/134: ✗ FAILED
   Error: unindent does not match any outer indentation level (<string>, line 34)
HumanEval/135: ✗ FAILED
HumanEval/136: ✗ FAILED
HumanEval/137: ✗ FAILED
   Error: '(' was never closed (<string>, line 61)
HumanEval/138: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 77) (<string>, line 64)
HumanEval/139: ✗ FAILED
   Error: Missing parentheses in call to 'print'. Did you mean print(...)? (<string>, line 16)
HumanEval/140: ✗ FAILED
   Error: unterminated triple-quoted string literal (detected at line 145) (<string>, line 131)
HumanEval/141: ✗ FAILED
HumanEval/142: ✗ FAILED
HumanEval/143: ✗ FAILED
   Error: maximum recursion depth exceeded
HumanEval/144: ✗ FAILED
   Error: test2
HumanEval/145: ✗ FAILED
   Error: maximum recursion depth exceeded while getting the repr of an object
HumanEval/146: ✗ FAILED
HumanEval/147: ✗ FAILED
HumanEval/148: ✗ FAILED
   Error: object of type 'NoneType' has no len()
HumanEval/149: ✗ FAILED
HumanEval/150: ✗ FAILED
   Error: invalid syntax (<string>, line 117)
HumanEval/151: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/152: ✗ FAILED
   Error: This prints if this assert fails 1 (good for debugging!)
HumanEval/153: ✗ FAILED
HumanEval/154: ✗ FAILED
   Error: test #0
HumanEval/155: ✗ FAILED
HumanEval/156: ✗ FAILED
   Error: invalid syntax (<string>, line 13)
HumanEval/157: ✗ FAILED
   Error: '(' was never closed (<string>, line 106)
HumanEval/158: ✗ FAILED
   Error: unexpected indent (<string>, line 12)
HumanEval/159: ✗ FAILED
   Error: Error
HumanEval/160: ✗ FAILED
HumanEval/161: ✗ FAILED
HumanEval/162: ✗ FAILED
HumanEval/163: ✗ FAILED
   Error: Test 1

In [ ]:
completions = pd.read_csv('/content/human-eval/model_completions.csv')
completions

In [23]:
model_name

'meta-llama/CodeLlama-7b-Python-hf'

In [24]:
from human_eval.data import read_problems, write_jsonl
import itertools
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm import tqdm

problems = read_problems()

# model_name = "meta-llama/Llama-3.2-3B"
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# tokenizer.pad_token = tokenizer.eos_token


# # Apply 4-bit quantization
# # bnb_config = BitsAndBytesConfig(
# #     load_in_4bit=True,
# #     bnb_4bit_compute_dtype=torch.float16,
# #     bnb_4bit_use_double_quant=True,
# #     bnb_4bit_quant_type="nf4"
# # )

# model = AutoModelForCausalLM.from_pretrained(
#     model_name,
#     #quantization_config=bnb_config,
#     device_map="auto"
# )

samples_first = []
samples_second = []
for problem_id in tqdm(problems.keys()):
    #  Prompt 1
    coding_prompt = problems[problem_id]["prompt"]
    prompt1_header = "You are an expert Python programmer, and here is your task: Complete the following python function: \n"
    prompt1 = prompt1_header + coding_prompt
    input1 = tokenizer(prompt1, return_tensors="pt").to(model.device)

    output1 = model.generate(
        input1.input_ids,
        max_length=500,
        temperature=0.2,
        top_p=0.95,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
    )
    generated_code1 = tokenizer.decode(output1[0], skip_special_tokens=True)

    completion1 = generated_code1[len(prompt1):] # remove header and coding prompt

    # Prompt 2
    prompt2_header = "There might be an error in the code below because of lack of understanding of the question. Please correct the error, if any, and rewrite the solution. Only output the final correct Python program! \n"
    prompt2 = prompt2_header + generated_code1[len(prompt1_header):] # adds just the coding portion of prompt 1's response

    input2 = tokenizer(prompt2, return_tensors="pt").to(model.device)

    output2 = model.generate(
        input2.input_ids,
        max_length=1000,
        temperature=0.2,
        top_p=0.95,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
    )
    generated_code2 = tokenizer.decode(output2[0], skip_special_tokens=True)

    completion2 = generated_code2[len(prompt2_header) + len(coding_prompt):] # remove header and coding prompt

    samples_first.append({
        "task_id": problem_id,
        "completion": completion1
    })

    samples_second.append({
        "task_id": problem_id,
        "completion": completion2
    })

write_jsonl("humaneval_samples1.jsonl", samples_first)
write_jsonl("humaneval_samples2.jsonl", samples_second)

  0%|          | 0/164 [00:00<?, ?it/s]The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
100%|██████████| 164/164 [1:06:22<00:00, 24.28s/it]

In [ ]:
import gc
torch.cuda.empty_cache()
gc.collect()

In [25]:
!evaluate_functional_correctness humaneval_samples1.jsonl

Reading samples...
164it [00:00, 7456.54it/s]
Running test suites...
100% 164/164 [00:03<00:00, 50.34it/s]
Writing results to humaneval_samples1.jsonl_results.jsonl...
100% 164/164 [00:00<00:00, 54359.56it/s]
{'pass@1': 0.27439024390243905}

In [26]:
!evaluate_functional_correctness humaneval_samples2.jsonl

Reading samples...
164it [00:00, 7162.14it/s]
Running test suites...
100% 164/164 [00:03<00:00, 50.25it/s]
Writing results to humaneval_samples2.jsonl_results.jsonl...
100% 164/164 [00:00<00:00, 37965.88it/s]
{'pass@1': 0.2865853658536585}

In [27]:
import json

file_path = "humaneval_samples1.jsonl_results.jsonl"
data = []

with open(file_path, "r") as f:
    for line in f:
        data.append(json.loads(line.strip()))

data_dict1 = {i: item for i, item in enumerate(data)}

file_path = "humaneval_samples2.jsonl_results.jsonl"
data = []

with open(file_path, "r") as f:
    for line in f:
        data.append(json.loads(line.strip()))

data_dict2 = {i: item for i, item in enumerate(data)}

In [28]:
# Get Results
count_i_c = 0
count_c_i = 0
correct_1 = 0
correct_2 = 0
num_problems = len(problems)
for i in range(len(data_dict1)):
    if data_dict1[i]['passed']:
        correct_1 += 1
    if data_dict2[i]['passed']:
        correct_2 += 1
    if data_dict1[i]['passed'] and not data_dict2[i]['passed']:
        count_c_i += 1
    elif not data_dict1[i]['passed'] and data_dict2[i]['passed']:
        count_i_c += 1

print("Accuracy@t1: " + str(correct_1 / num_problems))
print("Accuracy@t2: " + str(correct_2 / num_problems))
print("delta(t1,t2): " + str((correct_2 - correct_1) / num_problems))
print("delta(t1,t2) i to c: " + str(count_i_c / num_problems))
print("delta(t2,t1) c to i: " + str(count_c_i / num_problems))

Accuracy@t1: 0.27439024390243905
Accuracy@t2: 0.2865853658536585
delta(t1,t2): 0.012195121951219513
delta(t1,t2) i to c: 0.018292682926829267
delta(t2,t1) c to i: 0.006097560975609756